<!-- Estrutura da pagina  -->  
<section id="corpo">
    <div id="estatico">
        <div id="container_d">
            <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong>Campanhas de Vacinação</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 
            <div class="left"></div>
            

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">


                <!-- "conteudo"  -->                         
                <h4><a name="base" id="base"> <img src="/images/st_gear.png" /></a>  <strong>Confira aqui as vacinas e datas de campanhas de vacinação que serão realizadas em 2013:</strong><br/>
                </h4>
                <hr />
                <p style="margin-left: 5%;"><br />
                </p>
                <!-- Inicio calendário de Adultos"  -->                    
                <table class="reference">
                    <tbody> 
                        <tr>
                            <th>Campanha de Vacinação</th>
                            <th>data</th>

                        </tr>


                        <tr>
                            <td>Contra a influenza</td>
                            <td>15 a 26 de abril</td>

                        </tr>

                        <tr>
                            <td>Contra poliomielite</td>
                            <td>15 a 28 de junho</td>


                        <tr>
                            <td>Multivacinação</td>
                            <td>24 a 30 de agosto</td>

                        </tr>

                        <tr>
                            <td>Hepatite B 1ª dose</td>
                            <td>15 a 26 de abril</td>

                        </tr>

                        <tr>
                            <td>Hepatite B 2ª dose</td>
                            <td>15 a 28 de junho</td>

                        </tr>

                        <tr>
                            <td>Hepatite B 3ª dose</td>
                            <td>19 de outubro</td>

                        </tr>



                        <tr>
                            <th></th>
                            <th></th>


                        </tr>

                    </tbody>
                </table>	 
                <!-- Fim calendário de Adultos"  -->
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />



            </div>
        </div>

        <div class="right">
        </div>
    </div>
</div>
<div style="clear:both;">
</div>                
</section>