<!-- Estrutura da pagina  -->  
<section id="corpo">
    
    <div id="estatico">
        <div id="container_d"> 
            
             <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong>Legislação</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 
            <div class="left"></div>
            
            

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">
                <p style="text-align: justify;">&nbsp;</p>                           
                <!-- "conteudo"  -->                            
                <p><strong>	<img src="/images/st_direito.png" /> Vacinação de idosos</strong> </p>

                <p style="margin-left: 5%;">A pessoa idosa tem direito a receber do SUS vacinas necessárias à; prevenvção de doenças. </p>
                <p style="margin-left: 10%;"><img src="/images/bullet.gif" /></span>Amparo legal: </p>
                <p style="margin-left: 10% ;"><a href="http://www.planalto.gov.br/ccivil_03/Leis/2003/L10.741.htm" target="_blank"> - Lei  nº 10.741, de 01 de outubro de 2003, Artigo 15, Parágrafo 2º</a>;</p>
                <p style="margin-left: 10%;"><a href="http://bvsms.saude.gov.br/bvs/saudelegis/gm/2010/prt3318_28_10_2010.html" target="_blank">-  Portaria nº 3.318, de 28 de outubro 2010</a>
                </p>


                <p><strong> <img src="/images/st_direito.png" /> Vacinação infantil</strong> </p>
                <p style="margin-left: 5%;">As crianças e os adolescentes têm direito a receber do SUS a vacinaço necessária à prevenção de doenças.</p>
                <p style="margin-left: 10%;"><img src="/images/bullet.gif" /></span>Amparo legal: </p>
                <p style="margin-left: 10% ;"><a href="http://www.planalto.gov.br/ccivil_03/Leis/L8069.htm" target="_blank">- Lei  nº 8.069, de 13 de junho de 1990, Artigo 14, Parágrafo Único;</a></p>
                <p style="margin-left: 10%;"><a href="http://bvsms.saude.gov.br/bvs/saudelegis/gm/2010/prt3318_28_10_2010.html" target="_blank">-  Portaria nº 3.318, de 28 de outubro 2010</a>
                </p>


                <p><strong> <img src="/images/st_direito.png" /> Legislações específicas:</strong></p>
                <p style="margin-left: 5%;">Outras legislações referentes a vacinação.</p>
                <p style="margin-left: 10%;"><img src="/images/bullet.gif" /></span>Amparo legal: </p>
                <p style="margin-left: 10% ;"><a href="http://www.planalto.gov.br/ccivil_03/leis/l6360.htm" target="_blank">- Lei nº 6.360, de 23/09/1976 - Remedios;</a></p>
                <p style="margin-left: 10% ;"><a href="http://www.sgc.goias.gov.br/upload/arquivos/2012-05/instrucao-normativa-o.-1-de-19-de-agosto-de-2004.pdf" target="_blank">- Lei nº 8.069, de 13/06/</a><a href="http://bvsms.saude.gov.br/bvs/publicacoes/diretrizes_nacionais_atencao_saude_adolescentes_jovens_promocao_saude.pdf">1990</a><a href="http://www.sgc.goias.gov.br/upload/arquivos/2012-05/instrucao-normativa-o.-1-de-19-de-agosto-de-2004.pdf" target="_blank">: ECA;</a></p>
                <p style="margin-left: 10% ;"><a href="http://portal.saude.gov.br/portal/arquivos/pdf/lei8080.pdf" target="_blank">- Lei nº 8080, de 19-/10/1990 - Sa&uacute;de;</a></p>
                <p style="margin-left: 10%;"><a href="http://www.sgc.goias.gov.br/upload/arquivos/2012-05/instrucao-normativa-o.-1-de-19-de-agosto-de-2004.pdf" target="_blank">- Instrução Normativa nº 1, de 19/08/2004 - Gestão dos imunobiológicos;</a></p>
                <p style="margin-left: 10%;"><a href="http://portal.saude.gov.br/portal/arquivos/pdf/lei8080.pdf" target="_blank"></a></p>

                </p>


            </div>
        </div>

        <div class="right">
        </div>
    </div>
</div>
<div style="clear:both;">
</div>                
</section>
