<!-- Estrutura da pagina  -->  
<section id="corpo">
    <div id="estatico">
        <div id="container_d"> 
            <div class="left"></div>
            <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong>Vacinas</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">


                <!-- "conteudo"  -->                         
                <h4><a name="base" id="base"> <img src="/images/st_gear.png" /></a>  <strong>Confira abaixo todas as vacinas e suas caracteristicas:</strong><br/>
                </h4>
                <hr />
                <p style="margin-left: 5%;"><br />
                </p>
                <ul>
                    <li><a href="#bcg">Vacina BCG</a></li>
                    <li><a href="#ati">Vacina Antitetânica - ATT</a></li>
                    <li><a href="#dt">Vacina - Antitetânica e Antidiftérica (dt) - Dupla Bacteriana do Adulto</a></li>
                    <li><a href="#dtpa_vip_polio">Vacina - Tríplice Bacteriana Acelular do Adulto com vacina inativada da poliomielite(dTpa-VIP) - difteria/ tetano/ coqueluche/Polio</a></li>
                    <li><a href="#dtpa_adulto">Vacina - Tríplice Bacteriana Acelular do Adulto (DTPa) - difteria/ tétano/ coqueluche</a></li>
                    <li><a href="#varicela">Vacina - Varicela</a></li>
                    <li><a href="#influenza_b">Vacina -<em>Haemofilus influenza b</em></a></li>
                    <li><a href="#hep_b">Vacina - Hepatite B</a></li>
                    <li><a href="#hep_a">Vacina - Hepatite A</a></li>
                    <li><a href="#hep_a+b">Vacina - Hepatite A + B</a></li>
                    <li><a href="#gripe">Vacina - Gripe (Influenza)</a></li>
                    <li><a href="#triplice_viral">Vacina - Sarampo / Caxumba / Rubéola (Tríplice Viral)</a></li>
                    <li><a href="#tetra_viral">Vacina - Sarampo / Caxumba / Rubéola/ Varicela (Tetra Viral)</a></li>
                    <li><a href="#poliomelite">Vacina - Poliomelite</a></li>
                    <li><a href="#pneumococicas_conjugadas">Vacina - Pneumocócicas Conjugadas (10-valente e 13-valente)</a></li>
                    <li><a href="#pneumococica_polissacaridica">Vacina - Pneumocócicas Polissacarídica 23-valente</a></li>
                    <li><a href="#meningococica_conjugada_acwy">Vacina - Meningocócica conjugada ACWY</a></li>
                    <li><a href="#meningococica_conjugada">Vacina - Meningocócica C Conjugada</a></li>
                    <li><a href="#meningococica_polissacaridica">Vacina - Meningocócica Polissacarídica A+C</a></li>
                    <li><a href="#hpv">Vacina - HPV</a></li>
                    <li><a href="#raiva">Vacina - Raiva</a></li>
                    <li><a href="#tifoide">Vacina - Febre Tifóide</a></li>
                    <li><a href="#rotavirus">Vacina - Rotavírus</a></li>
                    <li><a href="#febre_amarela">Vacina - Febre Amarela</a></li>
                </ul>
                <p><a name="bcg" id="bcg"></a><strong>Vacina BCG</strong>&nbsp;<a href="#base"><a href="/index/consultar-vacinas"><img src="/images/subir.png" />&nbsp; Topo</a></p>
                <p><strong>Indicação:</strong>&nbsp;Proteção;o contra formas graves de tuberculose e contactantes de pacientes com hanseníase.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crianças a partir do nascimento e adultos.</p>
                <p><strong>Contraindicões</strong>&nbsp;AIDS e outras imunodeficiências congênitas ou adquiridas. Fase aguda de infecçõees de pele generalizada.</p>
                <p><strong>Esquema de doses:</strong><br />
                    1ª dose: a partir do nascimento<br />
                    Reforço: não se recomenda mais.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Adenopatias locais, ndulos frios ou quentes.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intrad&eacute;rmica.</p>
                <p>&nbsp;</p>
                <p><a name="ati" id="ati"></a><strong>Vacina Antitet&acirc;nica - ATT</strong>&nbsp;<a href="#base"><a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><br /></p>
                <p>A vacina contra o t&eacute;tano existe em combina&ccedil;&otilde;es com outras vacinas e a escolha e a indica&ccedil;&atilde;o da apresenta&ccedil;&atilde;o s&atilde;o prerrogativas do m&eacute;dico.</p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra t&eacute;tano em todas as idades.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crian&ccedil;as, adultos e idosos.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:</strong>&nbsp;N&atilde;o h&aacute;, exceto as contra-indica&ccedil;&otilde;es gerais de todas as vacinas: quadro febril agudo e intenso ou alergia a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong>&nbsp;Esta vacina n&atilde;o est&aacute; recomendada em esquemas de vacina&ccedil;&atilde;o de rotina. Sua indica&ccedil;&atilde;o &eacute; restrita e deve ser analisada pelo m&eacute;dico.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Febre, dor e vermelhid&atilde;o local.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="dt" id="dt"></a><strong>Vacina - Antitet&acirc;nica e Antidift&eacute;rica (dt) - Dupla Bacteriana do Adulto</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a>&nbsp;<br />
                    <em>A vacina contra a difteria e o t&eacute;tano existe em combina&ccedil;&otilde;es com outras vacinas e a escolha e a indica&ccedil;&atilde;o da apresenta&ccedil;&atilde;o s&atilde;o prerrogativas do m&eacute;dico.</em></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra t&eacute;tano e difteria, usada a partir de 7 anos de idade.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crian&ccedil;as maiores de 7 anos, adultos, idosos e gestantes.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:</strong>&nbsp;Contraindica&ccedil;&otilde;es gerais de todas as vacinas: quadro febril agudo ou alergia grave a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as acima de 7 anos e adultos n&atilde;o vacinados ou com vacina&ccedil;&atilde;o desconhecida: tr&ecirc;s doses com intervalos de dois meses entre as doses. A partir da&iacute;, refor&ccedil;os a cada 10 anos.<br />
                    Crian&ccedil;as acima de 7 anos e adultos com esquema prim&aacute;rio de tr&ecirc;s doses completo: uma dose de refor&ccedil;o a cada 10 anos. Mas preferencialmente deve-se utilizar a vacina tr&iacute;plice bacteriana acelular do tipo adulto (dTpa).<br />
                    Gestantes: uma dose ou mais (dependendo do hist&oacute;rico vacinal), preferencialmente a partir do segundo trimestre da gesta&ccedil;&atilde;o. No puerp&eacute;rio, uma dose da vacina tr&iacute;plice bacteriana acelular do tipo adulto (dTpa).</p>
                <p><strong>Eventos&nbsp;Adversos:</strong>&nbsp;Febre, dor e vermelhid&atilde;o local. </p>
                <p><strong>Via de Aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p><a name="dtpa_vip_polio" id="dtpa2"></a><strong>Vacina - Tr&iacute;plice Bacteriana Acelular do Adulto com vacina inativada da poliomielite(dTpa-VIP) - difteria/ t&eacute;tano/ coqueluche/Polio&nbsp;&nbsp;</strong><a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra a difteria, t&eacute;tano, coqueluche e poliomielite nos adolescentes e adultos.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;adolescentes, adultos e idosos. A vacina &eacute; licenciada para crian&ccedil;as a partir de 3 anos de idade, mas para crian&ccedil;as at&eacute; 12 anos de idade, &eacute; prefer&iacute;vel a formula&ccedil;&atilde;o infantil da vacina tr&iacute;plice bacteriana com a vacina inativada da poliomielite (DTPa &ndash; VIP).</p>
                <p><strong>Contra-indica&ccedil;&otilde;es:&nbsp;</strong>Quadro febril agudo ou hipersensibilidade aos componentes da vacina (anafilaxia), encefalopatia dentro de 7 dias ap&oacute;s vacina&ccedil;&atilde;o seguindo a imuniza&ccedil;&atilde;o pr&eacute;via de vacina com o componente pertussis (coqueluche).</p>
                <p><strong>Esquema de doses:</strong>&nbsp;Crian&ccedil;as maiores, adolescentes e adultos n&atilde;o vacinados com DTP, DTPa ou DT ou com hist&oacute;rico vacinal desconhecido: tr&ecirc;s doses com intervalo de dois meses entre elas, sendo uma dose de dTpa-VIP e as seguintes com dT. A partir da&iacute;, refor&ccedil;os a cada 10 anos com dTpa-VIP.</p>
                <p>Crian&ccedil;as maiores, adolescentes e adultos com esquema vacinal incompleto: completar o esquema com uma ou duas doses, sendo uma s&oacute; dose com dTpa-VIP e as demais com dT.</p>
                <p>Crian&ccedil;as maiores, adolescentes e adultos com esquema prim&aacute;rio de tr&ecirc;s doses completo: refor&ccedil;os de 10 em 10 anos com uma dose de dTpa-VIP.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Febre, dor e vermelhid&atilde;o local.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="dtpa" id="dtpa"></a><strong>Vacina - Tr&iacute;plice Bacteriana Pedi&aacute;trica Acelular (DTPa) - Difteria/ T&eacute;tano/ Coqueluche</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a><br />
                    <em>A vacina contra a difteria, o t&eacute;tano e a coqueluche pode estar combinada com outras vacinas e a escolha e a indica&ccedil;&atilde;o da apresenta&ccedil;&atilde;o s&atilde;o prerrogativas do m&eacute;dico.</em></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra a difteria, t&eacute;tano e coqueluche. A vacina acelular &eacute; menos reatog&ecirc;nica do que a vacina de c&eacute;lulas inteiras dos postos de sa&uacute;de. Integra a rotina de vacina&ccedil;&atilde;o para crian&ccedil;as a partir dos 2 meses aos 7 anos de idade.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:</strong>&nbsp;Crian&ccedil;as a partir de 7 anos de idade; hipersensibilidade aos componentes da vacina (anafilaxia), encefalopatia dentro de 7 dias ap&oacute;s vacina&ccedil;&atilde;o imuniza&ccedil;&atilde;o pr&eacute;via da vacina com o componente pertussis (coqueluche); alergia grave (anafilaxia) a componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong>&nbsp;3 doses+ refor&ccedil;os - a primeira dose com 2 meses de idade, a segunda com 4 meses e a terceira com 6 meses. Um refor&ccedil;o aos 15 meses e outro refor&ccedil;o entre 4 e 6 anos de idade. Ap&oacute;s isso, refor&ccedil;o de 10 em 10 anos com a vacina DT(dupla do tipo adulto) ou, preferencialmente, com a vacina dTpa (tr&iacute;plice bacteriana acelular do tipo adulto).</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Febre e rea&ccedil;&otilde;es locais (dor, vermelhid&atilde;o e edema) s&atilde;o as mais comuns. Raramente pode ocorrer: irrita&ccedil;&atilde;o, choro intenso (beb&ecirc;s), s&iacute;ndrome hipot&ocirc;nica-hiporresponsiva.</p>
                <p><strong>Apresenta&ccedil;&otilde;es:</strong>&nbsp;Vacina tr&iacute;plice bacteriana acelular pedi&aacute;trica: DTPa. Vacina tr&iacute;plice combinada a outras vacinas:<br />
                    Tetra Hib - DTPa + Hib (tr&iacute;plice + hem&oacute;filo B)<br />
                    Tetra HB - DTPa + HB (tr&iacute;plice + hepatite B)<br />
                    Tetraxim - DTPa + IPV (tr&iacute;plice + p&oacute;lio inativada)<br />
                    Penta - DTPa + Hib + IPV (tr&iacute;plice + hem&oacute;filo B + p&oacute;lio inativada)<br />
                    Hexa - DTPa + Hib + IPV + HB (tr&iacute;plice + hem&oacute;filo B + p&oacute;lio inativada + Hepatite B<br />
                    As vacinas DTPa e as combinadas s&atilde;o apresentadas em monodose; apresenta&ccedil;&otilde;es com hem&oacute;filo B t&ecirc;m li&oacute;filo a ser dilu&iacute;do.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="dtpa_adulto" id="dtpa_adulto"></a><strong>Vacina - Tr&iacute;plice Bacteriana Acelular do Adulto (DTPa) - difteria/ t&eacute;tano/ coqueluche</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra a difteria, t&eacute;tano e coqueluche nos adolescentes e adultos.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crian&ccedil;as a partir de 10 anos, adolescentes, adultos e idosos.</p>
                <p><strong>Contra-indica&ccedil;&otilde;es:</strong>&nbsp;Quadro febril agudo ou hipersensibilidade aos componentes da vacina (anafilaxia), encefalopatia dentro de 7 dias ap&oacute;s vacina&ccedil;&atilde;o seguindo a imuniza&ccedil;&atilde;o pr&eacute;via de vacina com o componente pertussis (coqueluche).</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as a partir de 10 anos de idade e adultos n&atilde;o vacinados com DTP, DTPa ou DT ou com hist&oacute;rico vacinal desconhecido: tr&ecirc;s doses com intervalo de dois meses entre elas, sendo uma dose de dTpa e as seguintes com dT. A partir da&iacute;, refor&ccedil;os a cada 10 anos com dTpa.<br />
                    Crian&ccedil;as a partir de 10 anos e adultos com esquema vacinal incompleto: completar o esquema com uma ou duas doses, sendo uma s&oacute; dose com dTpa e as demais com dT.<br />
                    Crian&ccedil;as a partir de 10 anos e adultos com esquema prim&aacute;rio de tr&ecirc;s doses completo: refor&ccedil;os de 10 em 10 anos com uma dose de dTpa.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Febre, dor e vermelhid&atilde;o local.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="varicela" id="varicela"></a><strong>Vacina - Varicela</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra a varicela (catapora).</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crian&ccedil;as a partir de 12 meses de idade e adultos.</p>
                <p><strong>Contra-indica&ccedil;&otilde;es:</strong>&nbsp;Imunodeprimidos, gestantes, crian&ccedil;as menores de 9 meses, alergia grave a componentes da vacina ou a dose pr&eacute;via da vacina (anafilaxia).</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as de 12 meses at&eacute; 2 anos: 2 doses, a primeira a partir dos 12 meses de idade e a segunda aos 2 anos de idade, respeitando-se intervalo m&iacute;nimo de 3 meses. A aplica&ccedil;&atilde;o a partir de 9 meses deve ser feita sob orienta&ccedil;&atilde;o m&eacute;dica.<br />
                    Crian&ccedil;as maiores de 2 anos e menores de 13 anos: 2 doses, segunda 3 meses ap&oacute;s a primeira.<br />
                    Crian&ccedil;as maiores de 13 anos e adultos: 2 doses com intervalo de 1 a 2 meses entre elas.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Podem ocorrer 7 a 15 dias ap&oacute;s a aplica&ccedil;&atilde;o: quadro brando de les&otilde;es na pele semelhantes &agrave; varicela.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Subcut&acirc;nea ou intramuscular.</p>
                <p>Obs: Apenas a vacina do laborat&oacute;rio GSK est&aacute; licenciada para aplica&ccedil;&atilde;o em crian&ccedil;as a partir dos nove meses de idade.</p>
                <p>&nbsp;</p>
                <p><a name="influenza_b" id="influenza_b"></a><strong>Vacina -&nbsp;<em>Haemofilus influenza b</em></strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra infec&ccedil;&otilde;es invasivas causadas pelo&nbsp;<em>Haemophilus influenzae</em>&nbsp;tipo b (meningite, pericardite, pneumonia, artrite e osteomielite).</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;A vacina integra a rotina de imuniza&ccedil;&atilde;o infantil e pode ser recomendada para adultos e idosos em situa&ccedil;&otilde;es de risco para doen&ccedil;as causadas pelo&nbsp;<em>Haemophilus influenzae</em>&nbsp;tipo b.<br />
                    A VACINA PODE ESTAR COMBINADA COM OUTRAS VACINAS OU ISOLADAMENTE. A ESCOLHA E A INDICA&Ccedil;&Atilde;O S&Atilde;O PRERROGATIVAS DO M&Eacute;DICO.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:</strong>&nbsp;Tanto para a vacina simples quanto para a vacina combinada, apenas as contraindica&ccedil;&otilde;es gerais de todas as vacinas: quadro febril agudo ou alergia grave (anafilaxia) a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as a partir de 2 meses: tr&ecirc;s doses, aos 2, 4 e aos 6 meses de idade, e um refor&ccedil;o aos 15 meses de idade.<br />
                    Indiv&iacute;duos com riscos especiais: dose &uacute;nica.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;S&atilde;o raros e geralmente locais. Podem ocorrer nas 24/48 horas seguintes &agrave; aplica&ccedil;&atilde;o.</p>
                <p><strong>Apresenta&ccedil;&otilde;es:</strong><br />
                    Vacina Simples:&nbsp;<em>Haemofilus Influenza b</em><br />
                    Vacinas Combinadas: Tetra Hib: Tr&iacute;plice bacteriana acelular (DTPa) + Hib<br />
                    PENTA: Tr&iacute;plice Bacteriana acelular (DTPa) + Hib + P&oacute;lio injet&aacute;vel<br />
                    HEXA: Tr&iacute;plice Bacteriana acelular (DTPa) + Hib + P&oacute;lio injet&aacute;vel + Hepatite B</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="hep_b" id="hep_b"></a><strong>Vacina - Hepatite B</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra a hepatite causada pelo v&iacute;rus B.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crian&ccedil;as, adultos e idosos. A vacina integra a rotina de imuniza&ccedil;&atilde;o infantil, mas &eacute; recomendada para indiv&iacute;duos de todas as idades.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:</strong>&nbsp;Gerais de todas as vacinas: quadro febril agudo ou alergia grave (anafilaxia) a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as e adultos: tr&ecirc;s doses, sendo a segunda um ou dois meses ap&oacute;s a primeira, e a terceira seis meses ap&oacute;s a primeira dose. A primeira dose das crian&ccedil;as deve ser administrada nas primeiras 12 a 24 horas de vida, pois 90% dos rec&eacute;m-nascidos que s&atilde;o contaminados durante o parto desenvolvem hepatite cr&ocirc;nica.<br />
                    Prematuros com menos de 2000g ou 36 semanas de gesta&ccedil;&atilde;o: quatro doses, sendo a primeira com 12 a 24 horas de vida, a segunda com um m&ecirc;s de idade, a terceira um m&ecirc;s ap&oacute;s a segunda dose e a terceira seis meses ap&oacute;s a segunda dose.<br />
                    Imunodeprimidos e pacientes renais cr&ocirc;nicas: &eacute; necess&aacute;rio analisar resposta imunol&oacute;gica para se avaliar necessidade de modifica&ccedil;&atilde;o deste esquema, conforme indica&ccedil;&atilde;o m&eacute;dica.<br />
                    <strong>Obs:</strong>&nbsp;no sistema p&uacute;blico, em virtude da vacina de tr&iacute;plice de c&eacute;lulas inteiras combinada &agrave; vacina do hem&oacute;filo b e da hepatite B ser a &uacute;nica dispon&iacute;vel para a rotina das crian&ccedil;as at&eacute; 6 meses de idade, uma dose extra da vacina da hepatite B precisou ser acrescentada aos 4 meses de idade</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Raros (menos de 5%). Geralmente rea&ccedil;&otilde;es locais (calor, vermelhid&atilde;o, dor), at&eacute; 24 ap&oacute;s a aplica&ccedil;&atilde;o.</p>
                <p><strong>Apresenta&ccedil;&otilde;es:</strong><br />
                    Vacina Simples: Vacina hepatite B infantil e adulto<br />
                    Vacinas Combinadas: Vacina Hepatite A e B: Hepatite A + Hepatite B<br />
                    Hexa: Tr&iacute;plice acelular (DTPa) + Hib + IPV + Hepatite B (infantil)</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="hep_a" id="hep_a"></a><strong>Vacina - Hepatite A</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:</strong>&nbsp;Prote&ccedil;&atilde;o contra a hepatite causada pelo v&iacute;rus A, que &eacute; transmitido por &aacute;gua e alimentos contaminados, principalmente em &aacute;reas end&ecirc;micas e com saneamento b&aacute;sico prec&aacute;rio.</p>
                <p><strong>Quem pode se vacinar:</strong>&nbsp;Crian&ccedil;as a partir de 1 ano de idade, adultos e idosos.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:</strong>&nbsp;Quadro febril agudo ou alergia grave (anafilaxia) a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong>&nbsp;2 doses, sendo a segunda 6 meses ap&oacute;s a primeira. A escolha da formula&ccedil;&atilde;o pedi&aacute;trica ou adulta depender&aacute; da idade do paciente.</p>
                <p><strong>Eventos Adversos:</strong>&nbsp;Raros (menos de 5%). Rea&ccedil;&otilde;es locais s&atilde;o as mais comuns, at&eacute; 24 ap&oacute;s a aplica&ccedil;&atilde;o.</p>
                <p><strong>Apresenta&ccedil;&otilde;es:</strong><br />
                    Vacina Simples: Vacina Hepatite A adulto e pedi&aacute;trica<br />
                    Vacinas Combinadas: Vacina Hepatite A e B.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="hep_a+b" id="hep_a+b"></a><strong>Vacina - Hepatite A + B</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra as hepatites causadas pelo v&iacute;rus A e pelo v&iacute;rus B.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 1 ano, adultos e idosos n&atilde;o vacinados anteriormente contra as duas hepatites.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Apenas as contra-indica&ccedil;&otilde;es gerais de todas as vacinas: quadro febril agudo ou alergia grave (anafilaxia) a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as de 1 ano at&eacute; 15 anos de idade (inclusive):<br />
                    Com a vacina infantil - tr&ecirc;s doses, sendo a segunda um m&ecirc;s ap&oacute;s a primeira, e a terceira seis meses ap&oacute;s a primeira.<br />
                    Com a vacina adulto - duas doses, sendo a segunda seis meses ap&oacute;s a primeira.<br />
                    A partir de 16 anos, adultos e idosos: tr&ecirc;s doses da vacina do adulto, sendo a segunda um m&ecirc;s ap&oacute;s a primeira, e a terceira seis meses ap&oacute;s a primeira.<br />
                    Imunodeprimidos e pacientes renais cr&ocirc;nicos: &eacute; necess&aacute;rio analisar resposta imunol&oacute;gica para se avaliar o n&uacute;mero de doses necess&aacute;rias al&eacute;m das normais, sob orienta&ccedil;&atilde;o m&eacute;dica.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>Iaros (menos de 5%). Rea&ccedil;&otilde;es locais s&atilde;o as mais comuns, at&eacute; 24 ap&oacute;s a aplica&ccedil;&atilde;o.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="gripe" id="gripe"></a><strong>Vacina - Gripe (Influenza)</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra infec&ccedil;&otilde;es causadas por v&iacute;rus influenza (gripe) e suas complica&ccedil;&otilde;es.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 6 meses, adultos e idosos.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Quadro febril agudo, alergia (anafilaxia) a um dos componentes da vacina, alergia (anafilaxia) &agrave; prote&iacute;na de ovo.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as de 6 a 35 meses: no primeiro ano em que s&atilde;o vacinadas, duas doses de 0,25 ml com intervalo de um m&ecirc;s entre elas. A partir de ent&atilde;o, doses &uacute;nicas anuais.<br />
                    Crian&ccedil;as de 3 a 8 anos: no primeiro ano em que s&atilde;o vacinadas, duas doses 2 doses de 0,5 ml com intervalo de um m&ecirc;s entre elas. A partir de ent&atilde;o, doses &uacute;nicas anuais.<br />
                    Adultos e crian&ccedil;as a partir de 9 anos: dose &uacute;nica anual de 0,5 ml.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>Febre, dor e vermelhid&atilde;o no local da aplica&ccedil;&atilde;o at&eacute; 24/48 horas ap&oacute;s a vacina&ccedil;&atilde;o.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="triplice_viral" id="triplice_viral"></a><strong>Vacina - Sarampo / Caxumba / Rub&eacute;ola (Tr&iacute;plice Viral)</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra rub&eacute;ola, caxumba, sarampo e suas complica&ccedil;&otilde;es.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 12 meses, adultos e idosos.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Imunodeprimidos, gestantes, quadro febril agudo e alergia grave (anafilaxia) a um dos componentes da vacina, alergia grave a ovo de galinha (anafilaxia).</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as a partir de 12 meses: uma dose, e refor&ccedil;o entre 2 e 4 anos.<br />
                    Crian&ccedil;as a partir de 2 anos de idade e adultos: duas doses com intervalo de quatro meses. A vacina pode ser aplicada a qualquer momento, em qualquer idade, exceto durante a gesta&ccedil;&atilde;o. Idealmente todo adulto deve ter a comprova&ccedil;&atilde;o de duas doses da vacina, aplicadas em qualquer momento da vida.<br />
                    OBS: para mulheres em idade f&eacute;rtil, &eacute; recomendado evitar engravidar nos 30 dias seguintes &agrave; vacina&ccedil;&atilde;o.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>Raros, mas quadro gripal com ou sem exantema ou aumento da par&oacute;tida podem surgir 10 dia ap&oacute;s a aplica&ccedil;&atilde;o.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Subcut&acirc;nea ou intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="tetra_viral" id="tetra_viral"></a><strong>Vacina - Sarampo / Caxumba / Rub&eacute;ola / Varicela (Tetra Viral)</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra rub&eacute;ola, caxumba, sarampo, varicela e suas complica&ccedil;&otilde;es.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 12 meses at&eacute; 12 anos de idade.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Imunodeprimidos, gestantes, quadro febril agudo e alergia grave (anafilaxia) a um dos componentes da vacina, alergia grave a ovo de galinha (anafilaxia).</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as a partir de 12 meses: uma dose aos 12 meses e refor&ccedil;o entre 2 e 4 anos.<br />
                    Crian&ccedil;as a partir de 2 anos at&eacute; 12 anos de idade: duas doses com intervalo de tr&ecirc;s meses.&nbsp;<br />
                    OBS: para mulheres em idade f&eacute;rtil, &eacute; recomendado evitar engravidar nos 30 dias seguintes &agrave; vacina&ccedil;&atilde;o.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>Raros, mas quadro gripal com ou sem exantema, pequeno n&uacute;mero de ves&iacute;culas na pele ou aumento da par&oacute;tida podem surgir 10 dia ap&oacute;s a aplica&ccedil;&atilde;o.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Subcut&acirc;nea ou intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="poliomelite" id="poliomelite"></a><strong>Vacina - Poliomelite</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra a infec&ccedil;&atilde;o pelo v&iacute;rus da p&oacute;lio e suas complica&ccedil;&otilde;es (paralisia infantil). A vacina oral contra a poliomielite (VOP) s&oacute; est&aacute; dispon&iacute;vel apenas no sistema p&uacute;blico. A vacina injet&aacute;vel isolada da poliomielite (VIP) s&oacute; est&aacute; dispon&iacute;vel na rede p&uacute;blica. Na rede privada est&aacute; dispon&iacute;vel em formula&ccedil;&atilde;o combinada com outras vacinas.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 2 meses. A vacina VIP &eacute; tamb&eacute;m recomendada para indiv&iacute;duos que ir&atilde;o viajar para locais onde a doen&ccedil;a &eacute; end&ecirc;mica.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Quadro febril agudo ou alergia a um dos componentes da vacina. A apresenta&ccedil;&atilde;o oral &eacute; de v&iacute;rus vivos, sendo portanto contraindicada em pacientes imunodeficientes. A apresenta&ccedil;&atilde;o injet&aacute;vel &eacute; inativada, n&atilde;o havendo esta contraindica&ccedil;&atilde;o.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as a partir dos 2 meses: tr&ecirc;s doses, aos 2, 4 e 6 meses de idade, um refor&ccedil;o aos 15 meses e outro refor&ccedil;o aos 4-5 anos.<br />
                    Indiv&iacute;duos que viajar&atilde;o para &aacute;reas de risco: dose &uacute;nica de VIP.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>A vacina oral pode raramente causar rea&ccedil;&otilde;es gastrintestinais discretas. A vacina injet&aacute;vel pode causar eventos locais como dor e vermelhid&atilde;o.</p>
                <p><strong>Apresenta&ccedil;&otilde;es:</strong><br />
                    Vacina simples: VIP - indispon&iacute;vel comercialmente no momento.<br />
                    VOP - dispon&iacute;vel em postos de sa&uacute;de<br />
                    Vacinas combinadas: Penta: dTPa + Hib + VIP (Tr&iacute;plice + Hem&oacute;filo b + p&oacute;lio injet&aacute;vel)<br />
                    Hexa: dTPa + Hib + VIP + Hepatite B (Tr&iacute;plice + Hem&oacute;filo b + p&oacute;lio injet&aacute;vel + hepatite B)<br />
                    Tetraxim: dTPa+VIP (Tr&iacute;plice +p&oacute;lio injet&aacute;vel)<br />
                    dTpa+VIP (Tr&iacute;plice +p&oacute;lio injet&aacute;vel do adolescente e adulto)</p>
                <p>&nbsp;</p>
                <p><a name="pneumococicas_conjugadas" id="pneumococicas_conjugadas"></a><strong>Vacina - Pneumoc&oacute;cicas Conjugadas (10-valente e 13-valente)</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra infec&ccedil;&otilde;es invasivas causadas pelo pneumococo.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>A vacina pneumoc&oacute;cica 13-valente, que se utiliza da mesma plataforma tecnol&oacute;gica da antiga vacina 7-valente, mas tem acrescentados mais seis sorogrupos de pneumococos aos sete sorogrupos originais &eacute; licenciada para crian&ccedil;as a partir de 2 meses at&eacute; 6 anos de idade incompletos. A vacina pneumoc&oacute;cica 10-valente est&aacute; licenciada para crian&ccedil;as a partir de 2 meses at&eacute; 2 anos de idade.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Quadro febril agudo ou alergia grave a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as de 2 a 6 meses de idade: tr&ecirc;s doses + refor&ccedil;o - primeira dose o mais precocemente poss&iacute;vel, a partir de 2 meses de vida, segunda dose 2 meses ap&oacute;s a primeira, terceira dose 4 meses ap&oacute;s a primeira. Refor&ccedil;o aos 15 meses.<br />
                    Obs: quando a vacina&ccedil;&atilde;o &eacute; iniciada fora desta faixa et&aacute;ria, o esquema de vacina&ccedil;&atilde;o pode sofrer altera&ccedil;&otilde;es.</p>
                <p><strong>OBS:</strong>&nbsp;Idosos, crian&ccedil;as e adolescentes portadores de doen&ccedil;as de risco, para infec&ccedil;&atilde;o pneumoc&oacute;cica (imunodeprimidos, cardiopatas e pneumopatas, aspl&ecirc;nicos, entre outras) podem receber uma ou duas dose da vacina pneumoc&oacute;cica 13-valente, independentemente do hist&oacute;rico vacinal pr&eacute;vio.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>Dor, vermelhid&atilde;o e endura&ccedil;&atilde;o locais. Pode haver sintomatologia sist&ecirc;mica, como febre, perda de apetite, irritabilidade.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="pneumococica_polissacaridica" id="pneumococica_polissacaridica"></a><strong>Vacina - Pneumoc&oacute;cica Polissacar&iacute;dica 23-valente</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra a infec&ccedil;&atilde;o pelo pneumococo. Indicada para pacientes a partir de 2 anos de idade com doen&ccedil;a de base que os coloquem em risco para a doen&ccedil;a (diabetes, cardio e pneumopatias, esplenectomizados, etc) e idosos. N&atilde;o &eacute; vacina de escolha para imuniza&ccedil;&atilde;o b&aacute;sica de crian&ccedil;as. Deve ser considerada como rotina para maiores de 60 anos.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 2 anos de idade, adultos e idosos.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Quadro febril agudo ou alergia grave a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:&nbsp;</strong>Somente a partir dos 2 anos de idade em dose &uacute;nica. Sob orienta&ccedil;&atilde;o m&eacute;dica, pode ser indicado APENAS UM refor&ccedil;o ap&oacute;s 5 anos.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:&nbsp;</strong>Dor, vermelhid&atilde;o e endura&ccedil;&atilde;o locais. Pode haver febre.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="meningococica_conjugada_acwy" id="meningococica_conjugada2"></a><strong>Vacina meningoc&oacute;cica conjugada ACWY&nbsp;</strong><a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra infec&ccedil;&otilde;es graves causadas pelos meningococos tipo A, C, W e Y (meningite, meningococcemia).<br />
                    <br />
                    <strong>Quem pode se vacinar:</strong>&nbsp;A vacina est&aacute; licenciada no Brasil para pessoas a partir de 11 anos de idade, inclusive adultos, mas em outros pa&iacute;ses a partir de 2 anos de idade.<br />
                    Contraindica&ccedil;&otilde;es: apenas as contraindica&ccedil;&otilde;es gerais de todas as vacinas: quadro febril agudo ou alergia grave (anafilaxia) a um dos componentes da vacina.<br />
                    <br />
                    <strong>Esquema de doses:</strong>&nbsp;Crian&ccedil;as, adolescentes e adultos, em dose &uacute;nica. Refor&ccedil;os somente sob crit&eacute;rio m&eacute;dico.<br />
                    <br />
                    <strong>Eventos Adversos:</strong>&nbsp;S&atilde;o raros e geralmente locais. Podem ocorrer nas 24/48 horas seguintes &agrave; aplica&ccedil;&atilde;o.<br />
                    <br />
                    <strong>Apresenta&ccedil;&otilde;es:</strong>&nbsp;Vacina meningoc&oacute;cica ACWY, conjugada ao CRM197<br />
                    <strong><br />
                        Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="meningococica_conjugada" id="meningococica_conjugada"></a><strong>Vacina - Meningoc&oacute;cica C Conjugada</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra as meningites causadas pelos meningococo tipo C.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 2 meses, adolescentes, adultos e idosos.</p>
                <p><strong>Contra-indica&ccedil;&otilde;es:&nbsp;</strong>Quadro febril agudo ou alergia grave a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Crian&ccedil;as de 2 meses a 6 meses de idade: primeira dose o mais precocemente poss&iacute;vel a partir de 2 meses de vida, a segunda dose 2 meses ap&oacute;s a primeira, um refor&ccedil;o aos 15 meses, um refor&ccedil;o 5 a 6 anos ap&oacute;s &uacute;ltima dose e um refor&ccedil;o entre 11 e 12 anos de idade. Refor&ccedil;os posteriores dever&atilde;o ser avaliados por m&eacute;dicos, em situa&ccedil;&otilde;es de risco.<br />
                    Obs: quando a vacina&ccedil;&atilde;o &eacute; iniciada fora desta faixa et&aacute;ria, o esquema de vacina&ccedil;&atilde;o pode sofrer altera&ccedil;&otilde;es.<br />
                    Adolescentes e adultos: uma dose. Doses adicionais dever&atilde;o ser avaliados por m&eacute;dicos, em situa&ccedil;&otilde;es de risco.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:&nbsp;</strong>Dor, vermelhid&atilde;o, endura&ccedil;&atilde;o locais. Raramente febre e irritabilidade.</p>
                <p><strong>Apresenta&ccedil;&otilde;es:</strong><br />
                    Vacina para Meningite C Conjugada com Tox&oacute;ide Dift&eacute;rico - Meningitec (Pfizer)<br />
                    Vacina para Meningite C Conjugada com Tox&oacute;ide Tet&acirc;nico - Neisvac-C (Baxter)<br />
                    Vacina para Meningite C Conjugada com Tox&oacute;ide Dift&eacute;rico - Menjugate (Novartis)</p>
                <p>&nbsp;</p>
                <p><a name="meningococica_polissacaridica" id="meningococica_polissacaridica"></a><strong>Vacina - Meningoc&oacute;cica Polissacar&iacute;dica A+C</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&atilde;o:&nbsp;</strong>Prote&ccedil;&atilde;o contra as meningites causadas pelos meningococo tipo A e C.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as a partir de 2 anos, adolescentes, adultos e idosos. Essa vacina s&oacute; deve ser usada em situa&ccedil;&otilde;es especiais, tais como epidemias e viagens para locais onde haja risco de meningite por meningococo A. No Brasil, no momento, n&atilde;o existe circula&ccedil;&atilde;o do meningococo A. Por ser vacina com efic&aacute;cia menor, sem mem&oacute;ria imunol&oacute;gica e sem efic&aacute;cia em menores de 2 anos de idade, N&Atilde;O &Eacute; VACINA USADA DE ROTINA, necessitando prescri&ccedil;&atilde;o m&eacute;dica espec&iacute;fica.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Menores de 2 anos de idade e as contra-indica&ccedil;&otilde;es gerais de todas as vacinas: quadro febril agudo ou alergia grave a um dos componentes da vacina.</p>
                <p><strong>Esquema de doses:&nbsp;</strong>Dose &uacute;nica, a partir de 2 anos de idade.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:&nbsp;</strong>Dor, vermelhid&atilde;o e endura&ccedil;&atilde;o locais.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="hpv" id="hpv"></a><strong>Vacina - HPV</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><br />
                    <em>Atualmente existem duas vacinas diferentes contra o HPV. Cabe ao m&eacute;dico decidir qual vacina ser&aacute; recomendada.</em></p>
                <p><strong>Indica&ccedil;&otilde;es:&nbsp;</strong>Protege contra as doen&ccedil;as causadas pelo papiloma v&iacute;rus humano (HPV). Alguns tipos de HPV est&atilde;o envolvidos no surgimento das verrugas genitais (ou condilomas) e outros tipos relac ionam-se ao desenvolvimento de c&acirc;ncer genital (colo de &uacute;tero, vulva, vagina, p&ecirc;nis, &acirc;nus). Virtualmente todo c&acirc;ncer de colo de &uacute;tero &eacute; causado por infec&ccedil;&atilde;o pelo HPV.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Meninas e mulheres dos 9 aos 26 anos. Mulheres de outras faixas et&aacute;rias s&oacute; com apresenta&ccedil;&atilde;o da prescri&ccedil;&atilde;o m&eacute;dica espec&iacute;fica. Idealmente, a vacina&ccedil;&atilde;o deve ser feita antes do in&iacute;cio da atividades sexuais - entre 11 e 12 anos de idade, ou mesmo antes, a partir de 9 anos de idade. A vacina quadrivalente do HPV foi licenciada pela ANVISA, em 23/05/2011, para meninos e homens entre 9 e 26 anos de idade, para preven&ccedil;&atilde;o das verrugas genitais e c&acirc;ncer anal e peniano; &nbsp;tamb&eacute;m deve ser recomendada o mais cedo poss&iacute;vel, a partir de 9 anos de idade.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Hipersensibilidade aos componentes da vacina (anafilaxia), rea&ccedil;&atilde;o al&eacute;rgica importante ap&oacute;s alguma anterior dose desta vacina, gesta&ccedil;&atilde;o (pois n&atilde;o existem estudos de seguran&ccedil;a).</p>
                <p><strong>Esquema de doses:&nbsp;</strong>3 doses, sendo a segunda um ou dois meses ap&oacute;s a primeira (dependendo da vacina utilizada) e a terceira seis meses ap&oacute;s a primeira.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:&nbsp;</strong>Raras e geralmente locais (dor, vermelhid&atilde;o, incha&ccedil;o, prurido). Rea&ccedil;&atilde;o sist&ecirc;mica (febre) tamb&eacute;m &eacute; rara.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular.</p>
                <p>&nbsp;</p>
                <p><a name="raiva" id="raiva"></a><strong>Vacina - Raiva</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&otilde;es:&nbsp;</strong>Imuniza&ccedil;&atilde;o contra a raiva em humanos, na profilaxia pr&eacute;-exposi&ccedil;&atilde;o (vacina&ccedil;&atilde;o preventiva) e na profilaxia p&oacute;s-exposi&ccedil;&atilde;o (vacina&ccedil;&atilde;o curativa).<br />
                    &Eacute; NECESS&Aacute;RIA ORIENTA&Ccedil;&Atilde;O M&Eacute;DICA DO ESQUEMA DE VACINA&Ccedil;&Atilde;O QUE SER&Aacute; FEITO, ASSIM COMO ACOMPANHAMENTO PELO M&Eacute;DICO ASSISTENTE.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Todo e qualquer indiv&iacute;duo em risco de contrair raiva, independentemente da idade, uma vez que &eacute; doen&ccedil;a de alt&iacute;ssima letalidade e contra a qual n&atilde;o existe tratamento espec&iacute;fico.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Em virtude da evolu&ccedil;&atilde;o fatal da infec&ccedil;&atilde;o pelo v&iacute;rus r&aacute;bico, a profilaxia p&oacute;s-exposi&ccedil;&atilde;o n&atilde;o apresenta contra-indica&ccedil;&atilde;o. Em caso de vacina&ccedil;&atilde;o preventiva (profilaxia pr&eacute;-exposi&ccedil;&atilde;o), as contra-indica&ccedil;&otilde;es s&atilde;o as gerais de todas as vacinas.</p>
                <p><strong>Esquema de doses:&nbsp;</strong>Deve ser definido e controlado por m&eacute;dico. A dose da vacina para crian&ccedil;as &eacute; a mesma do adulto.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:&nbsp;</strong>Em geral, de intensidade leve e tendem desaparecer espontaneamente em 48 horas. A ocorr&ecirc;ncia de anafilaxia &eacute; rara.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular ou subcut&acirc;nea.</p>
                <p>&nbsp;</p>
                <p><a name="tifoide" id="tifoide"></a><strong>Vacina - Febre Tif&oacute;ide</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&otilde;es:&nbsp;</strong>Prote&ccedil;&atilde;o contra infec&ccedil;&atilde;o pela Salmonella Typhi, causadora da febre tif&oacute;ide. Indicada para pessoas que se dirigem para regi&otilde;es onde a febre tif&oacute;ide ocorre endemicamente ou em surtos.<br />
                    &Eacute; NECESS&Aacute;RIA ORIENTA&Ccedil;&Atilde;O M&Eacute;DICA PARA AVALIA&Ccedil;&Atilde;O DA NECESSIDADE DA VACINA&Ccedil;&Atilde;O.</p>
                <p><strong>Quem pode se vacinar:&nbsp;</strong>Crian&ccedil;as acima de 2 anos de idade e adultos.</p>
                <p><strong>Contraindica&ccedil;&otilde;es:&nbsp;</strong>Hipersensibilidade a algum componente da vacina.</p>
                <p><strong>Esquema de doses:&nbsp;</strong>Dose &uacute;nica e, caso o indiv&iacute;duo permane&ccedil;a em risco ou volte a se expor ao risco, deve ser feita a revacina&ccedil;&atilde;o a cada 3 anos.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:</strong>&nbsp;Locais, de intensidade leve e tendem desaparecer espontaneamente em at&eacute; 48 horas. A ocorr&ecirc;ncia rea&ccedil;&otilde;es sist&ecirc;micas e de anafilaxia &eacute; rara.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Intramuscular ou subcut&acirc;nea.</p>
                <p>&nbsp;</p>
                <p><a name="rotavirus" id="rotavirus"></a><strong>Vacina - Rotav&iacute;rus</strong>&nbsp;&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&otilde;es:</strong>&nbsp;Imuniza&ccedil;&atilde;o contra infec&ccedil;&otilde;es gastrintestinais causadas pelo rotav&iacute;rus.<br />
                    EXISTEM DUAS VACINAS DIFERENTES CONTRA O ROTAV&Iacute;RUS, COM ESQUEMAS VACINAIS DIFERENTES. A ESCOLHA ENTRE AS VACINAS &Eacute; PRERROGATIVA M&Eacute;DICA.</p>
                <p><strong>Quem pode ser vacinar:&nbsp;</strong>Beb&ecirc;s a partir de 6 semanas de vida, SENDO QUE A PRIMEIRA DOSE PODE SER FEITA NO M&Aacute;XIMO AT&Eacute; 14 SEMANAS DE VIDA.</p>
                <p><strong>Contra-indica&ccedil;&otilde;es:&nbsp;</strong>Imunodefici&ecirc;ncia cong&ecirc;nita ou adquirida; uso de imunossupressores (quimioterapia, radioterapia); rea&ccedil;&atilde;o al&eacute;rgica grave a um dos componentes da vacina; doen&ccedil;a gastrintestinal cr&ocirc;nica; malforma&ccedil;&atilde;o cong&ecirc;nita do trato digestivo; hist&oacute;ria pr&eacute;via de invagina&ccedil;&atilde;o (intussuscep&ccedil;&atilde;o) intestinal, quadro febril agudo moderado a grave.</p>
                <p><strong>Esquema de doses:</strong><br />
                    Vacina Rotarix&reg;: duas doses, a primeira a partir de 6 semanas e antes de 32 semanas de vida. O intervalo entre as doses deve ser de 2 meses, aceitando-se um m&iacute;nimo de 4 semanas. A segunda dose n&atilde;o deve ser aplicada ap&oacute;s 7 MESES E 29 DIAS DE VIDA.<br />
                    Vacina RotaTeq&reg;: tr&ecirc;s doses, a primeira entre 6 e 12 semanas, a segunda entre 10 e 22 semanas e a terceira entre 14 e 32 semanas. A terceira dose n&atilde;o deve ser aplicada ap&oacute;s 32 semanas de vida.</p>
                <p><strong>Rea&ccedil;&otilde;es Adversas:&nbsp;</strong>Nenhum evento adverso espec&iacute;fico foi relacionado a estas vacinas at&eacute; ent&atilde;o.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:&nbsp;</strong>Ambas as vacinas t&ecirc;m aplica&ccedil;&atilde;o oral.</p>
                <p>&nbsp;</p>
                <p><a name="febre_amarela" id="febre_amarela"></a><strong>Vacina - Febre Amarela</strong>&nbsp;<a href="/index/consultar-vacinas"><img src="/images/subir.png" /></a>&nbsp; <a href="/index/consultar-vacinas">Topo</a><a href="#base"></a></p>
                <p><strong>Indica&ccedil;&otilde;es:</strong>&nbsp;Preven&ccedil;&atilde;o da febre amarela nas seguintes situa&ccedil;&otilde;es:</p>
                <ul>
                    <li>Para residentes de &aacute;reas end&ecirc;micas, como rotina;</li>
                    <li>Durante epidemias;</li>
                    <li>Para viajantes que se dirigem para &aacute;reas end&ecirc;micas.</li>
                </ul>
                <p><strong>Quem pode ser vacinar:</strong></p>
                <ul>
                    <li>Rotina para crian&ccedil;as a partir de 9 meses de idade, adolescentes e adultos em &aacute;reas end&ecirc;micas. Para controle de surto ou situa&ccedil;&atilde;o de alto risco, a vacina&ccedil;&atilde;o de crian&ccedil;as com idade entre 6 e 8 meses pode ser considerada pelo m&eacute;dico;</li>
                    <li>Para viajantes que se dirigem para &aacute;reas end&ecirc;micas, a partir de 9 meses de idade;</li>
                    <li>H&aacute; precau&ccedil;&otilde;es especiais para a administra&ccedil;&atilde;o em indiv&iacute;duos de 60 anos de idade ou mais (aumento de incid&ecirc;ncia de eventos adversos severos indesej&aacute;veis).</li>
                </ul>
                <p><strong>Contra-indica&ccedil;&otilde;es:</strong>&nbsp;Mulheres amamentando at&eacute; que seus beb&ecirc;s completem 6 meses de vida, imunodeprimidos, gestantes, indiv&iacute;duos com rea&ccedil;&atilde;o de hipersensibilidade ao ovo, prote&iacute;na de galinha, a qualquer componente da vacina ou hipersensibilidade grave (anafilaxia) ap&oacute;s dose anterior de vacina contra a febre amarela.</p>
                <p><strong>Esquema de doses:</strong>&nbsp;Dose &uacute;nica a cada 10 anos. Mesma dose de 0,5 mL para crian&ccedil;as e adultos.</p>
                <p><strong>Eventos Adversos:&nbsp;</strong>Podem ocorrer em cerca de 2% dos vacinados. Na maioria dos casos s&atilde;o rea&ccedil;&otilde;es locais, podendo tamb&eacute;m ocorrer dor de cabe&ccedil;a e mal-estar.</p>
                <p><strong>Via de aplica&ccedil;&atilde;o:</strong>&nbsp;Intramuscular ou subcut&acirc;nea.</p>
                <p>CERTIFICADO INTERNACIONAL DE VACINA&Ccedil;&Atilde;O E PROFILAXIA (CIVP)<br />
                    Para obter o CIVP, o indiv&iacute;duo dever&aacute; ser vacinado no m&iacute;nimo 10 dias antes de sua viagem para estar protegido contra a febre amarela. Essa vacina e o CIVP t&ecirc;m validade de 10 anos.</p>
                <p><strong>Aten&ccedil;&atilde;o:</strong>&nbsp;No momento da vacina&ccedil;&atilde;o, o indiv&iacute;duo recebe um certificado de vacina&ccedil;&atilde;o v&aacute;lido apenas no Brasil. Para realizar a troca pelo CIVP, dever&aacute; procurar pessoalmente os postos determinados pela ANVISA munido dos seguintes documentos.</p>



            </div>
        </div>

        <div class="right">
        </div>
    </div>
</div>
<div style="clear:both;">
</div>                
</section>