
 <!-- Estrutura da pagina  -->  
            <section id="corpo">
                <div id="estatico">
                  <div id="container_d"> 
                      <div class="conteudo">
                                
                                 <!-- Inicio tema principal  -->  
                                	<h3><strong>Calendário de Vacinação</strong></h3>
                        					<div class="hr">
											</div>
               			 		</div>
                          <!-- FIM tema principal  --> 
                         <div class="left"></div>
           			
                         
<!-- Inicio Leitura - "conteudo"  -->                           
	<div class="leitura">
                         
<!-- "conteudo"  -->
<br />
<a href="#infantil">Calendário de Vacinação Infantil</a><a href="#adolecente"><br />
Calendário de Vacinação Adolecente</a><br />
<a href="#idosos">Calendério de Vacinação Idosos</a> <br />
<br />


<!-- Inicio calendário de Crianças"  -->  
<table class="reference">
    <tbody>
    <tr> 
 	<a name="infantil" id="infantil"></a><h4><img src="/images/st_gear.png" /><strong> Calendário de Vacinação infantil </strong> </h4>
    </tr>
         
    	<tr>
    	  <th>IDADE</th>
    	  <th>VACINAS</th> 
    	  <th>DOSE</th>
    	  <th>DOENÇAS EVITADAS</th>
  	  </tr>
         <tr>
           <td height="102">Ao nascer</td>
           <td>BCG-ID</td>
           <td>Dose &uacute;nica</td>
           <td>Formas Graves da tuberculose (principalmente nas formas miliar meningea</td>
         </tr>
         
          <tr>
            <td>Hepatite B</td> 
            <td>1º dose</td>
            <td>Hepatite B</td>
          </tr>   
  
            <tr>
            <td>2 meses</td>
            <td> B</td> 
            <td>2º dose</td>
            <td>Hepatite B</td>
         </tr>
            <tr>
              <td rowspan="3">2 mês</td>
              <td>Pentav (DTP + hib)</td>
              <td rowspan="3">1º dose</td>
              <td>Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenza e tipo b</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>
            <tr>
              <td>&nbsp;</td>
              <td>&nbsp;</td>
            </tr>  
	</tbody>
</table>				  
<!-- Fim calendário de Crianças"  -->   
<br />  
<br />

<!-- Inicio calendário de Adultos"  -->                    
<table class="reference">
    <tbody>
 <tr> 
 	<a name="adolecente" id="adolecente"></a><h4><img src="/images/st_gear.png" /><strong> Calendário de Vacinação Adolecentes </strong> </h4>
         </tr> 
            <tr>
            <th>Vacinas</th>
            <th>Ao nascer</th>
            <th>1º mes</th>
            <th>2º mes</th>
            <th>4º mes</th>
            <th>6º mes</th>
            <th>9º mes</th>    
            <th>12º mes</th>  
            <th>15º mes</th>  
            <th>4 - 6 anos</th>  
            <th>10 anos</th>  
         </tr>
         
         
            <tr>
                <td>HEPATITE B </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
        
            <tr>
                <td>HEPATITE B</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>TETRAVALENTE</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>PÓLIO</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>ROTAVÍRUS</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>FEBRE AMARELA</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>TRÍPLICE VIRAL</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>TRÍPLICE BACTERIANA</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
      

            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>             
                <th></th>
                <th></th>
                <th></th>             
                <th></th>             
                <th></th>
                <th></th>   
                <th></th>                          
                        
           </tr>
  
	</tbody>
</table>	 
<!-- Fim calendário de Adultos"  -->   

<br />  <br /> 

<!-- Inicio calendário de idosos"  -->                   
<table class="reference">
    <tbody>
 <tr> 
 	<a name="idosos" id="idosos"></a><h4><img src="/images/st_gear.png" /><strong> Confira o Calendário de Vacinação Idosos </strong> </h4>
         </tr> 
            <tr>
            <th>Vacinas</th>
            <th>Ao nascer</th>
            <th>1º mes</th>
            <th>2º mes</th>
            <th>4º mes</th>
            <th>6º mes</th>
            <th>9º mes</th>    
            <th>12º mes</th>  
            <th>15º mes</th>  
            <th>4 - 6 anos</th>  
            <th>10 anos</th>  
         </tr>
         
         
            <tr>
                <td>BCG-ID</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
        
            <tr>
                <td>HEPATITE B</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>TETRAVALENTE</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>PÓLIO</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>ROTAVÍRUS</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>FEBRE AMARELA</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>TRÍPLICE VIRAL</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
            <tr>
                <td>TRÍPLICE BACTERIANA</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>        
            </tr>
             
      

            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>             
                <th></th>
                <th></th>
                <th></th>             
                <th></th>             
                <th></th>
                <th></th>   
                <th></th>                          
                        
           </tr>
  
	</tbody>
</table>
<!-- Fim calendário de idosos"  -->                  
                   	</div>
                    	</div>
                        
					<div class="right">
                    </div>
				</div>
			</div>
		<div style="clear:both;">
        </div>                
</section>