<!-- Estrutura da pagina  -->  
<section id="corpo">
    <div id="estatico">
        <div id="container_d"> 
            <div class="left"></div>
            <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong>Veja respostas para d&uacute;vidas comuns sobre vacina&ccedil;&atilde;o.</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">


                <!-- "conteudo"  -->                            
                <h4><img src="/images/st_gear.png" />  <strong>A vacina do posto de sa&uacute;de tem a mesma qualidade da vacina da cl&iacute;nica particular? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"> <img src="/images/st_direito.png" /> Sim. Cl&iacute;nicas e postos de sa&uacute;de s&atilde;o rigorosamente fiscalizados pela Vigil&acirc;ncia Sanit&aacute;ria. Deve-se estar atento &agrave;s condi&ccedil;&otilde;es de armazenamento das vacinas em consult&oacute;rios m&eacute;dicos, que nem sempre s&atilde;o t&atilde;o equipados quanto as cl&iacute;nicas e os postos de vacina&ccedil;&atilde;o.<br /><br /> 
                </p>

                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Por que algumas vacinas n&atilde;o fazem parte do calend&aacute;rio oficial?</strong><br/>
                </h4>
                <p style="margin-left: 5%;"> <img src="/images/st_direito.png" /> As vacinas s&atilde;o divididas conforme o uso: rotineiro (do calend&aacute;rio) e eventual, usadas com indica&ccedil;&atilde;o especial, como as contra gripe, raiva e meningite. <br /><br />
                </p>

                <hr />

                <h4><img src="/images/st_gear.png" /><strong> O programa brasileiro de vacinas &eacute; t&atilde;o bom quanto o de pa&iacute;ses desenvolvidos?</strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> Embora o governo brasileiro n&atilde;o tenha recursos suficientes para distribuir de gra&ccedil;a as vacinas dispon&iacute;veis no mercado, seu programa de imuniza&ccedil;&atilde;o &eacute; considerado um dos mais completos do mundo.<br /><br />
                </p>

                <hr />
                <h4><strong><img src="/images/st_gear.png" /> Existem vacinas para todas as doen&ccedil;as? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"> <img src="/images/st_direito.png" /> Ainda n&atilde;o, mas institui&ccedil;&otilde;es do mundo inteiro v&ecirc;m investindo cada vez mais nos processos de pesquisa e desenvolvimento de novas vacinas.<br /><br />
                </p>

                <hr />
                <h4><img src="/images/st_gear.png" /><strong> O programa brasileiro de vacinas &eacute; t&atilde;o bom quanto o de pa&iacute;ses desenvolvidos?</strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> Embora o governo brasileiro n&atilde;o tenha recursos suficientes para distribuir de gra&ccedil;a as vacinas dispon&iacute;veis no mercado, seu programa de imuniza&ccedil;&atilde;o &eacute; considerado um dos mais completos do mundo.<br /><br />
                </p>

                <hr />
                <h4><img src="/images/st_gear.png" /> <strong>Quais doen&ccedil;as foram erradicadas pela vacina&ccedil;&atilde;o? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> No Brasil, a vacina&ccedil;&atilde;o foi respons&aacute;vel pela erradica&ccedil;&atilde;o da var&iacute;ola e da poliomielite (paralisia infantil).<br /><br />
                </p>

                <hr />
                <h4><img src="/images/st_gear.png" /> <strong>Onde vacinar? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"> <img src="/images/st_direito.png" /> As vacinas consideradas obrigat&oacute;rias, segundo o Programa Nacional de Imuniza&ccedil;&otilde;es, do Minist&eacute;rio da Sa&uacute;de, podem ser encontradas nos Postos de Sa&uacute;de e tamb&eacute;m s&atilde;o aplicadas durante campanhas nacionais, e n&atilde;o custam nada.<br /><br />
                    J&aacute; as vacinas opcionais, que ainda n&atilde;o foram adotadas pelo governo, podem ser aplicadas em cl&iacute;nicas particulares, e t&ecirc;m pre&ccedil;os variados.<br />
                </p>

                <hr />
                <h4><strong><img src="/images/st_gear.png" /> O sistema imunol&oacute;gico natural &eacute; melhor do que a vacina&ccedil;&atilde;o? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> Uma infec&ccedil;&atilde;o permite que o sistema imunit&aacute;rio reaja de forma adequada, determinando prote&ccedil;&atilde;o permanente para quase todas as doen&ccedil;as. Mas doen&ccedil;as como a varicela, que habitualmente &eacute; benigna, podem levar &agrave; pneumonia; a poliomielite, &agrave; paralisia permanente; a caxumba, &agrave; surdez. E a vacina&ccedil;&atilde;o pode prevenir essas doen&ccedil;as e suas graves consequ&ecirc;ncias.<br />
                </p>

                <hr />
                <h4><strong><img src="/images/st_gear.png" /> Com quanto tempo a pessoa fica protegida ap&oacute;s a aplica&ccedil;&atilde;o de uma vacina? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"> <img src="/images/st_direito.png" />O desenvolvimento de anticorpos ocorre em m&eacute;dia, ap&oacute;s 15 dias da aplica&ccedil;&atilde;o vacinal.<br />
                </p>
                <hr />
                <h4><strong><img src="/images/st_gear.png" /> O que &eacute; calend&aacute;rio vacinal? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> &Eacute; uma sequ&ecirc;ncia cronol&oacute;gica de vacinas que se administram sistematicamente e cujo objetivo &eacute; obter uma imuniza&ccedil;&atilde;o adequada da popula&ccedil;&atilde;o contra as enfermidades para as quais se disp&otilde;e de vacinas<br />
                    <br />
                    Deve-se respeitar o n&uacute;mero de doses, os intervalos e aplica&ccedil;&atilde;o simult&acirc;nea entre as diferentes vacinas do calend&aacute;rio.</strong><br />
                </p>

                <hr />
                <h4><img src="/images/st_gear.png" /> <strong>Como &eacute; feita a vacina? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> A vacina &eacute; composta de bact&eacute;rias ou v&iacute;rus cultivados em laborat&oacute;rios. Estes agentes s&atilde;o tratados para que percam o seu poder de contaminar, mas n&atilde;o a capacidade de estimular a produ&ccedil;&atilde;o de anticorpos que s&atilde;o os respons&aacute;veis pela defesa do corpo. Podemos utilizar microrganismos mortos, fra&ccedil;&otilde;es deles ou ainda vivos e atenuados.<br /><br />
                    Algumas vacinas mais atuais utilizam t&eacute;cnicas de engenharia gen&eacute;tica, n&atilde;o se utilizando os microrganismos para confeccion&aacute;-las.<br />
                    <br />
                    ma vez que a vacina &eacute; aplicada, induz o organismo a produzir os anticorpos como se estivesse contaminado pelo agente, mas sem adoecer. A partir da&iacute;, toda vez que a pessoa entrar em contato com o &quot;germe de verdade&quot;, contra o qual foi vacinada, ir&aacute; produzir os anticorpos e estar&aacute; protegida.<br />
                </p>

                <hr />
                <h4><strong><img src="/images/st_gear.png" /> Por que vacinar quando as crian&ccedil;as s&atilde;o pequenas? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"><img src="/images/st_direito.png" /> Todas as crian&ccedil;as quando nascem, t&ecirc;m defesas contra algumas infec&ccedil;&otilde;es que a m&atilde;e tenha tido ou contra as quais tenha sido vacinada anteriormente, pois os anticorpos podem ser transmitidos atrav&eacute;s da placenta e do leite materno.<br />
                    <br />
                    Estas defesas transferidas pela m&atilde;e v&atilde;o se esgotando &agrave; medida que a crian&ccedil;a vai crescendo, surgindo a necessidade da fabrica&ccedil;&atilde;o de seus pr&oacute;prios anticorpos. &Eacute; justamente nessa fase da vida que as doen&ccedil;as s&atilde;o mais frequentes e costumam se apresentar de forma mais grave com maior mortalidade.<br />
                    <br />
                    As vacinas visam a prote&ccedil;&atilde;o dos pequenos beb&ecirc;s, e retardar seu in&iacute;cio &eacute; um equ&iacute;voco que deve ser evitado.<br />
                </p>

                <hr />
                <h4><strong><img src="/images/st_gear.png" /> Se houver atraso, necessito recome&ccedil;ar o esquema? </strong><br/>
                </h4>
                <p style="margin-left: 5%;"> <img src="/images/st_direito.png" /> Atrasos devem ser evitados, e sempre que poss&iacute;vel &agrave;s datas de retornos obedecidas. Eventuais pequenas antecipa&ccedil;&otilde;es ou atrasos n&atilde;o interferem na efic&aacute;cia da vacina, por&eacute;m existem vacinas que o atraso incidir&aacute; em reiniciar todo o esquema e outras, poder&aacute;, at&eacute; mesmo, perder o tempo exato da imuniza&ccedil;&atilde;o n&atilde;o podendo mais ser imunizado. Exemplo &eacute; rotav&iacute;rus infantil, se perder o prazo ideal para vacina&ccedil;&atilde;o, n&atilde;o poder&aacute; fazer vacina&ccedil;&atilde;o em adulto, pois atualmente n&atilde;o existe a vacina rotav&iacute;rus em adulto. <br /><br />
                </p>


            </div>
        </div>

        <div class="right">
        </div>
    </div>
</div>
<div style="clear:both;">
</div>                
</section>
