<div style="clear:both;"></div>
<div id="newsSlider">
    <div id="banner_div"></div>
    <script type="text/javascript" src="/assets/js/jquery.js"></script>					<!-- Transiçao da imagem -->
    <script type="text/javascript" src="/assets/js/jquery.flash.js"></script>				<!-- Transiçao da imagem -->
    <script type="text/javascript" src="/assets/js/jquery.dd.js"></script>					<!-- Transiçao da imagem -->
    <script type="text/javascript" src="/assets/js/jquery.lightbox.js"></script> 				<!-- Transiçao da imagem -->
    <script type="text/javascript" src="/assets/js/cycleFullTransitions2.js"></script>			<!-- Transiçao da imagem -->
    <link href='/assets/css/imagem.css' rel="stylesheet" type="text/css" />					<!-- Folha de estilo principal -->
    <script type="text/javascript" src="/assets/js/cookies.js"></script>					<!-- Cookies -->

    <div id="teaser">

        <script type="text/javascript">
            var N = 4;
            var width = 940;
            var atual = 1;
            var intervaloBanners = 6000;
            var intVar;
            var urlimgSel = 'url(images/st_controleativo.png)';
            var urlimg = 'url(images/st_controledesativo.png)';
            var heavyImage = new Image();
            var imagemL = Array("", "", "", ""); //Link das imagens caso necessario
            //var imagemB = Array("img/banner/st_001.jpg","img/banner/st_002.jpg","img/banner/st_003.jpg","img/banner/st_004.jpg"); //imagems
            var imagemB = Array("/banners/fotoban2_grande.jpg", "/banners/fotoban3_grande.jpg", "/banners/fotoban4_grande.jpg"); //imagems
            var fundos = Array("/banners/fotoban3_grande.jpg ", "/banners/fotoban3_grande.jpg", "/banners/fotoban4_grande.jpg"); //fundos
            var coresFnd = Array("#CDCDCD", "#182138", "#7DC4E8", "#CDCDCD"); //css das
            $(document).ready(function() {
                var w = width + 'px';
                $("#frameBanners").css({width: w});
                loopBanner();
                for (var i = 1; i <= N; i++) {
                    if (i == atual)
                        $("#cli" + i).css('background-image', urlimgSel);
                    else
                        $("#cli" + i).css('background-image', urlimg);
                }
                if ($.cookie("simov4") != null) {
                    if (Number($.cookie("simov4")) >= N)
                        atual = 1;
                    else
                        atual = Number($.cookie("simov4")) + 1;
                }
                muda(atual);
            });
            function muda(d) {
                atual = d;
                posicao = '-' + ((d - 1) * width) + 'px';
                for (var i = 1; i <= N; i++) {
                    if (i == atual)
                        $("#cli" + i).css('background-image', urlimgSel);
                    else
                        $("#cli" + i).css('background-image', urlimg);
                }

                heavyImage.src = "";
                heavyImage.src = fundos[atual - 1];
                heavyImage.onload = function() {
                    $("#disfarce").css("background-color", $('#bg').css('background-color'));
                    $("#disfarce").css("background-image", $('#bg').css('background-image'));
                    $("#disfarce").show(0);
                    $("#bg").css("background-image", "url(" + heavyImage.src + ")");
                    $("#bg").css("background-color", coresFnd[atual - 1]);
                    $("#disfarce").fadeOut(500);
                    if ($.browser.msie) {
                        $("#imgBan").hide(0);
                        $("#imgBan").attr("src", "");
                        $("#imgBan").attr("src", imagemB[atual - 1]);
                        document.getElementById("imgBan").onload = function() {
                            $("#imgBan").show(0);
                        };
                    }
                    else {
                        $("#imgBan").fadeOut(function() {
                            $("#imgBan").attr("src", "");
                            $("#imgBan").attr("src", imagemB[atual - 1]);
                            document.getElementById("imgBan").onload = function() {
                                $("#imgBan").fadeIn();
                            };
                        });
                    }
                    $("#linkBan").attr("href", imagemL[atual - 1]);
                    loopBanner();
                    $.cookie("simov4", atual, {
                        expires: 5
                    });
                };
            }
            function mudaInt() {
                if (atual == N)
                    atual = 1;
                else
                    atual = atual + 1;
                for (var i = 1; i <= N; i++) {
                    if (i == atual)
                        $("#cli" + i).css('background-image', urlimgSel);
                    else
                        $("#cli" + i).css('background-image', urlimg);
                }
                posicao = '-' + ((atual - 1) * width) + 'px';
                heavyImage.src = "";
                heavyImage.src = fundos[atual - 1];
                heavyImage.onload = function() {
                    $("#disfarce").css("background-color", $('#bg').css('background-color'));
                    $("#disfarce").css("background-image", $('#bg').css('background-image'));
                    $("#disfarce").show(0);
                    $("#bg").css("background-image", "url(" + heavyImage.src + ")");
                    $("#bg").css("background-color", coresFnd[atual - 1]);
                    $("#disfarce").fadeOut(500);
                    if ($.browser.msie) {
                        $("#imgBan").hide(0);
                        $("#imgBan").attr("src", "");
                        $("#imgBan").attr("src", imagemB[atual - 1]);
                        document.getElementById("imgBan").onload = function() {
                            $("#imgBan").show(0);
                        };
                    }
                    else {
                        $("#imgBan").fadeOut(function() {
                            $("#imgBan").attr("src", "");
                            $("#imgBan").attr("src", imagemB[atual - 1]);
                            document.getElementById("imgBan").onload = function() {
                                $("#imgBan").fadeIn();
                            };
                        });
                    }

                    $("#linkBan").attr("href", imagemL[atual - 1]);
                    loopBanner();
                    $.cookie("simov4", atual, {
                        expires: 5
                    });
                };
            }

            function loopBanner() {
                clearInterval(intVar);
                intVar = setInterval('mudaInt()', intervaloBanners);
            }
        </script>


        <div id="frameBanners">
            <ul>
                <li><img id="imgBan" src="/banners/fotoban1_grande.jpg" alt="" title="" style="display: inline-block;">
            </ul>
        </div>

        <div id="controle">
            <ul>
                <li><a href="javascript:muda(1)"><div id="cli1" class="btControl">&nbsp;</div></a></li>
                <li><a href="javascript:muda(2)"><div id="cli2" class="btControl">&nbsp;</div></a></li>
                <li><a href="javascript:muda(3)"><div id="cli3" class="btControl">&nbsp;</div></a></li>
                <li><a href="javascript:muda(4)"><div id="cli4" class="btControl">&nbsp;</div></a></li>
            </ul>
        </div>
    </div> 
</div>
<section>
    <script type="text/javascript"> $("#ultimasNoticias ul").idTabs();</script>

    <div id="newsSlider">
        <!-- primeira divisão da pag. principal -->	
        <div class="st_box">
            <div class="st_box_p">
                <h5><strong><img src="images/st_gear.png" /> Hospital Santa Maria<br/>
                    </strong><span style="margin-left: 5%;"><img src="images/bullet.gif" /> Mudança na vacinação infantil.</span></span></h5>
                <a id="foto_tumb" href="index.php?link=noticias"><img src="images/hospital_SM.jpg" alt="" width="150" height="100" border="0" class="st_conteudo_img"></a>
                <p>Tetravalente passa a incluir o imunizante contra a hepatite B e vai combater cinco enfermidades. A partir de agosto, as duas primeiras doses do composto para evitar a poliomielite serão injetáveis.<br>
                    <br>
                    A partir de agosto, o calendário de vacinação infantil sofrerá altereção. O Ministério da Saúde anunciou ontem que dois novos imunizantes serão incluídos. Com a novidade, em vez de as crianças tomarem as duas primeiras doses do composto contra a poliomielite em gotinhas, as aplicações... <br><b><a href="index.php?link=noticias">[Saiba mais]</a></b></p>
            </div>
        </div>
        <!-- fim primeira divisão da pag. principal -->	   


        <!-- segunda divisão da pag. principal -->
        <div class="st_box_a">
            <div class="st_box_pa">
                <h5> <img src="images/st_gear.png" /> SES-DF </h5>
                <span style="margin-left: 5%;"><img src="images/bullet.gif" /> Acesse agora o portal da saúde do DF</span></h5><br /><br />
                <a href="http://www.saude.df.gov.br/index.php" target="_blank" id="foto_tumb"><img src="images/ses.jpg" alt="" width="210" height="48" border="0"></a>
            </div>   
        </div>
        <!-- fim segunda divisão da pag. principal -->

        <!-- terceira divisão da pag. principal -->
        <div class="st_box_a">
            <div class="st_box_pa">

                <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
                <div style="text-align:center; margin:0 8px">
                    <h4>
                        <strong>
                            <img src="images/st_gear.png" /> Carteirinha Online
                            <br/> 
                        </strong></h4>
                    <hr />
                </div>

                <!-- Inicio Fazer acesso  --> 
                <span style="margin-left: 2%;">
                    <img src="images/bullet.gif" />
                    <b> Faça o login abaixo para ter acesso a carterinha de vacinação online.</b>
                </span>
                <!-- Fim Fazer acesso  -->   

                <!-- Inicio Formulários  -->
                <div>
                    <br>
                    <?php if (!$this->hasIdentity): ?>
                        <form class="form form-inline" action="/auth/login" method="post" name="frmFaleConosco" onsubmit="return submit_page(this);" > 
                            <div class="controls">
                                <label class="control-label"><b>Usuário:</b></label>
                                <div class="control-group">
                                    <input class="input" id="nome_login" name="nome_login" type="text" placeholder="Inserir seu nome"/>
                                </div>
                            </div>
                            <div class="controls">
                                <label class="control-label"><b>Senha:</b></label>
                                <div class="control-group">
                                    <input class="input" name="senha_login" type="password" placeholder="Insira sua senha" />
                                </div>
                            </div>
                            <!-- Fim Formulários  --> 

                            <!-- Inicio botões  do formulario-->
                            <div class="controls-row">
                                <button type="submit" class="btn btn-primary btn-small" name="enviar" id="signIn">Entrar</button>
                                <button type="reset" class="btn btn-small" name="reset" id="Limpar">Limpar </button>
                            </div>
                            <!-- Fim botões  do formulario-->

                            <!-- botao esqueceu a senha-->
                            <br>
                            <small><a href="/auth/recuperar">Esqueceu a senha?</a></small>
                            <!-- botao esqueceu a senha-->

                            <!-- inicio botao cadastro novo -->		
                            <small><a id="Cadastronovo" href="">Cadastrar Novo</a></small>
                        </form>
                    <?php else: ?>
                        <br>
                        <br>
                        <strong>Olá, <?php echo $this->user->nome_login ?> (<a href="/auth/logout"><strong>Sair</strong></a>)</strong>
                    <?php endif; ?>

                    <!-- Fim botao cadastro novo -->			
                </div>
            </div>
        </div>
        <!-- fim terceira divisão da pag. principal -->
    </div>
    <br />
    <div style="clear:both;"></div>
</section>
