<h1> SOBRE A INSTITUIÇÃO </h1>

<!-- Estrutura da pagina  -->  
<section id="corpo">
    <div id="estatico">
        <div id="container_d"> 
            <div class="left"></div>
            <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong> A Secretaria</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">

                <!-- "conteudo"  -->                            
                <h4><img src="/images/st_gear.png" /><strong> Quem Somos? </strong> </h4>
                <p style="margin-left: 5%;"><br />

                    <img src="/images/bullet.gif" /> A <strong>Secretaria de Saúde</strong> é o órgão do Poder Executivo do Distrito Federal responsável pela organização e elaboração de planos e políticas públicas voltadas para a promoção, prevenção e assist&ecirc;ncia &agrave; sa&uacute;de. &Eacute; fun&ccedil;&atilde;o da Secretaria de Sa&uacute;de dispor de condi&ccedil;&otilde;es para a prote&ccedil;&atilde;o e recupera&ccedil;&atilde;o da sa&uacute;de da popula&ccedil;&atilde;o, reduzindo as enfermidades, controlando as doen&ccedil;as end&ecirc;micas e parasit&aacute;rias e melhorando a vigil&acirc;ncia &agrave; sa&uacute;de, dando, assim, mais qualidade de vida aos moradores do Distrito Federal.<br />
                    <br />
                    A miss&atilde;o da Secretaria de Sa&uacute;de do Distrito Federal &eacute; aperfei&ccedil;oar o Sistema &Uacute;nico de Sa&uacute;de no &acirc;mbito do Distrito Federal, garantindo ao cidad&atilde;o atendimento de sa&uacute;de integral e humanizado.<br />
                    <br />
                    A vis&atilde;o &eacute; ser um sistema de sa&uacute;de que a popula&ccedil;&atilde;o conhe&ccedil;a, preze e confie, sendo excel&ecirc;ncia e refer&ecirc;ncia na aten&ccedil;&atilde;o integral &agrave; sa&uacute;de, apresentando os melhores indicadores de sa&uacute;de do pa&iacute;s.<br />
                    <br />
                </p>
                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Miss&atilde;o</strong></h4>
                <p style="margin-left: 5%;"><br />
                    <img src="/images/bullet.gif" /> &quot;Aperfei&ccedil;oar o Sistema &Uacute;nico de Sa&uacute;de no &acirc;mbito do Distrito Federal, garantindo ao cidad&atilde;o atendimento de sa&uacute;de integral e humanizado&quot;.<br />
                    <br />
                </p>
                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Vis&atilde;o</strong></h4>
                <p style="margin-left: 5%;"><br />
                    <img src="/images/bullet.gif" /> &quot;Ser um sistema de sa&uacute;de que a popula&ccedil;&atilde;o conhe&ccedil;a, preze e confie, sendo excel&ecirc;ncia e refer&ecirc;ncia na aten&ccedil;&atilde;o integral &agrave; sa&uacute;de, apresentando os melhores indicadores de sa&uacute;de do pa&iacute;s&quot;.<br />
                    <br />
                </p>
                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Funda&ccedil;&otilde;es, Autarquias e Org&atilde;os v&iacute;nculados</strong></h4>
                <p style="margin-left: 5%;"><br />
                    <img src="/images/bullet.gif" /> A Secretaria de Sa&uacute;de do Distrito Federal tem as seguintes funda&ccedil;&otilde;es, autarquias e &oacute;rg&atilde;os vinculados a ela que s&atilde;o:<br />
                    <br />
                </p>

                <ul type="disc"style="margin-left: 15%;">
                    <li> Funda&ccedil;&atilde;o Hemocentro de Bras&iacute;lia (FHB)<br />
                    </li>
                    <li> Funda&ccedil;&atilde;o de Ensino e Pesquisa em Ci&ecirc;ncias da Sa&uacute;de (FEPECS) <br />
                    </li>
                    <li>  Escola Superior de Ci&ecirc;ncias da Sa&uacute;de (ESCS)<br />
                    </li>
                    <li> Escola T&eacute;cnica de Sa&uacute;de de Bras&iacute;lia (ETESB) <br />
                    </li>
                    <li> Conselho de Sa&uacute;de do Distrito Federal (CSDF) <br />
                    </li>
                    <li>Laborat&oacute;rio Central (LACEN). </li> 
                    <br />
                </ul>
            </div>
        </div>

        <div class="right">
        </div>
    </div>
</div>
<div style="clear:both;">
</div>                
</section>