<h1> SOBRE A INSTITUIÇÃO </h1>

<!-- Estrutura da pagina  -->  
<section id="corpo">
    <div id="estatico">
        <div id="container_d"> 
            
            <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong> A Secretaria</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 
            <div class="left"></div>
             

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">

                <!-- "conteudo"  -->                            
                <h4><img src="/images/st_gear.png" /><strong> Quem Somos? </strong> </h4>
                <p style="margin-left: 5%;"><br />

                    <img src="/images/bullet.gif" /> A <strong>Secretaria de Saúde</strong> é o órgão do Poder Executivo do Distrito Federal responsável pela organização e elaboração de planos e políticas públicas voltadas para a promoção, prevenção e assistência à saúde. É função da Secretaria de Saúde dispor de condições para a proteção e recuperação da saúde da população, reduzindo as enfermidades, controlando as doenças endêmicas e parasitárias e melhorando a vigilância à saúde, dando, assim, mais qualidade de vida aos moradores do Distrito Federal.<br />
                    
                    <br />
                    A missão da Secretaria de Saúde do Distrito Federal é aperfeiçoar o Sistema Único de Saúde no âmbito do Distrito Federal, garantindo ao cidadão atendimento de saúde integral e humanizado.<br />
                    <br />
                    A visão é ser um sistema de saúde que a população conheça, preze e confie, sendo excelência e referência na atenção integral à saúde, apresentando os melhores indicadores de saúde do país.<br />
                    <br />
                </p>
                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Missão</strong></h4>
                <p style="margin-left: 5%;"><br />
                    <img src="/images/bullet.gif" /> "Aperfeiçoar o Sistema Único de Saúde no âmbito do Distrito Federal, garantindo ao cidadão atendimento de saúde integral e humanizado".<br />
                    <br />
                </p>
                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Visão</strong></h4>
                <p style="margin-left: 5%;"><br />
                    <img src="/images/bullet.gif" /> "Ser um sistema de saúde que a população conheça, preze e confie, sendo excelência e referência na atenção integral à saúde, apresentando os melhores indicadores de saúde do país".<br />
                    <br />
                </p>
                <hr />
                <h4><img src="/images/st_gear.png" /><strong> Fundações, Autarquias e Orgãos vinculados</strong></h4>
                <p style="margin-left: 5%;"><br />
                    <img src="/images/bullet.gif" /> A Secretaria de Saúde do Distrito Federal tem as seguintes fundações, autarquias e ôrgãos vinculados a ela que são:<br />
                    <br />
                </p>

                <ul type="disc"style="margin-left: 15%;">
                    <li> Fundação Hemocentro de Brasília (FHB)<br />
                    </li>
                    <li> Fundação de Ensino e Pesquisa em Ciências da Saúde (FEPECS) <br />
                    </li>
                    <li>  Escola Superior de Ciências da Saúde (ESCS)<br />
                    </li>
                    <li> Escola Técnica de Saúde de Brasília (ETESB) <br />
                    </li>
                    <li> Conselho de Saúde do Distrito Federal (CSDF) <br />
                    </li>
                    <li>Laboratório Central (LACEN). </li> 
                    <br />
                </ul>
            </div>
        </div>

        <div class="right">
        </div>
    </div>
</div>
<div style="clear:both;">
</div>                
</section>