<!-- Estrutura da pagina  -->  
<section id="corpo">
    <div id="estatico">
        <div id="container_d"> 
            <div class="left"></div>
            <div class="conteudo">

                <!-- Inicio tema principal  -->  
                <h3><strong>Links &Uacute;teis</strong></h3>
                <div class="hr">
                </div>
            </div>
            <!-- FIM tema principal  --> 

            <!-- Inicio Leitura - "conteudo"  -->                           

            <div class="leitura">

                <!-- "conteudo"  -->                            
                <h4><img src="/images/st_gear.png" /><strong> Links de Interesse:</strong><br/>
                </h4>
                <p><img src="/images/st_direito.png" /> Links 
                </p>


                <p style="margin-left: 5%;"><img src="/images/bullet.gif" /></span>Secretarias do MS:</p>
                <p style="margin-left: 10% ;"><a href="http://portalsaude.saude.gov.br/portalsaude/" target="_blank"> - Portal da Sa&uacute;de</a></p>
                <p style="margin-left: 10%;"><a href="http://www.ans.gov.br/" target="_blank">- ANS &ndash; Ag&ecirc;ncia Nacional de Sa&uacute;de Suplementar</a></p>
                <p style="margin-left: 10% ;"><a href="http://portal.anvisa.gov.br/wps/portal/anvisa/home" target="_blank">- ANVISA &ndash; Ag&ecirc;ncia Nacional de Vigil&acirc;ncia Sanit&aacute;ria</a></p>
                <p style="margin-left: 10%;"><a href="http://www.fiocruz.br/" target="_blank">- Fiocruz&ndash; Funda&ccedil;&atilde;o Oswaldo Cruz</a></p>
                <p style="margin-left: 10%;"><a href="http://www.ans.gov.br/" target="_blank">- ANS &ndash; Ag&ecirc;ncia Nacional de Sa&uacute;de Suplementar</a></p>


                <p style="margin-left: 5%;"><img src="/images/bullet.gif" /></span>Orgãos Colegiados:</p>				
                <p style="margin-left: 10% ;"><a href="http://www.conselho.saude.gov.br/" target="_blank">- CNS - Conselho Nacional de Sa&uacute;de</a></p>

                <p style="margin-left: 5%;"><img src="/images/bullet.gif" /></span>Área Jurídica:</p>				
                <p style="margin-left: 10% ;"><a href="http://portalsaude.saude.gov.br/portalsaude/index.cfm?portal=pagina.visualizararea&codarea=359&area=conjur/" target="_blank">- CONJUR</a></p>

                <p style="margin-left: 5%;"><img src="/images/bullet.gif" /></span>SUS:</p>				
                <p style="margin-left: 10% ;"><a href="http://www2.datasus.gov.br/DATASUS/index.php" target="_blank">- Data SUS</a></p>

                <p style="margin-left: 5%;"><img src="/images/bullet.gif" /></span>Secretária Estadual de Saúde:</p>				
                <p style="margin-left: 10% ;"><a href="http://www.saude.df.gov.br/" target="_blank">- SES DF</a></p>


            </div>                     							  
        </div>
    </div>

    <div class="right">
    </div>

<div style="clear:both;">
</div>                
</section>
