
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <!-- Titulo e Metas  -->
        <title>SIMOVA - Sistema de Monitoramento de Vacinas</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta http-equiv="window-target" content="_main" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Cache-Control" content="no-cache" />
        <meta http-equiv="X-UA-Compatible" content="IE=8"/> 
        <meta name="copyright" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="Robots" />
        <meta name="reply-to" content="itgills@gmail.com.br" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />  
        <!-- FINAL de Titulo e Metas  -->

        <!-- Inicio favicon  -->    
        <link href="favicon.ico" 	rel="shortcut icon" 	type="image/x-icon" />
        <link href="favicon.ico" 	rel="icon"		type="image/x-icon" />
        <link href="favicon.ico"	rel="shortcut icon" />
        <link href="favicon.png"	rel="apple-touch-icon" />
        <!-- Fim favicon  --> 

        <!-- JQuerys  -->        
        <!-- JQuerys  -->        
        <script src="/assets/js/jquery.js"></script> <!-- MENUS SUPERIORES --> 
        <script src="/assets/js/commons.js"></script> <!-- MENUS SUPERIORES -->  
        <script src="/assets/js/jquery.idTabs.js"></script> <!--  JPEG NO IE6 -->    
        <script src="/assets/js/swfobject.js"></script> <!--  Gera HTML/XHTML valido   -->   
        <!-- Fim JQuerys  -->
        <!-- Fim JQuerys  -->

        <!-- Adição de folhas de estilos  -->        
        <link href="/assets/css/stylesheet.css" rel="stylesheet" type="text/css" media="screen" />
        <link href="/assets/css/inicio.css" rel="stylesheet" type="text/css" media="screen" />

        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>


        <section id="container">
            <header>
                <div id="paisagem">
                    <a id="logo" href="/" title="Logo"></a>
                </div>
            </header>


            <!-- Inicio de Menus superior -->  
            <section id="content">
                <div id="left"></div>    
                <div id="menu" style="z-index:1000;">
                    <nav id="topnav">
                        <ul>
                            <li class="hs" id="tab_inicio"><a href="/">Início</a></li>
                            <li id="tab_empresa"><a href="/index/institucional">Institucional </a></li>
                            <li id="tab_servicos"><a href="#">Serviços</a>
                                <ul>
                                    <li><a href="/index/consultar-vacinas">Consultar Vacinas</a></li>
                                    <li><a href="/index/consultar-calendario">Consultar Calendário</a></li>
                                    <li><a href="/index/centro-saude"> Centros de Saúde</a></li>
                                    <li><a href="/index/consultar-legislacao">Consultar Legislação</a></li>
                                </ul>            
                            </li>

                            <li id="tab_campanha"><a href="/index/campanhas">CAMPANHAS</a></li>
                            <li id="tab_contato"><a href="/index/fale-conosco">FALE CONOSCO</a></li>                    
                        </ul>
                    </nav>
                </div>
                <!-- Links do menu em PHP -->  

                <script>$('#tab_inicio').addClass('selected');</script>

                <div id="right"></div> 
                <div id="bar">
                </div>




                <style type="text/css">
                    #corpo #newsSlider .st_box .st_box_p p .st_box_pa {
                        font-family: Verdana, Geneva, sans-serif;
                    }
                </style>
                
                <section id="corpo">

                <?php echo $this->layout()->content; ?>
                    
                </section>
                <!-- Inicio de Menus inferior --> 
                <footer><div class="top"></div>

                    <div class="box" style="border:none">
                        <h1>INSTITUCIONAL</h1>
                        <p><a href="/index/institucional">A Empresa </a></p>
                    </div>

                    <div class="box" style="width:120px;">
                        <h1>SERVIÇOS</h1>
                        <p><a href="/index/consultar-vacinas">Consultar Vacinas </a></p>
                        <p><a href="/index/consultar-calendario">Consultar Calendário</a></p>
                        <p><a href="/index/centro-saude">Consultar Centros de Saúde</a></p>
                        <p><a href="/index/consultar-legislacao">Consultar Legislação</a></p>
                    </div>

                    <div class="box" style="width:120px;">
                        <h1>Utilidades</h1>
                        <p><a href="/index/duvidas">Dúvidas Frequentes</a></p>
                        <p><a href="/index/links-uteis">Links Úteis</a></p>
                    </div>

                    <div class="box" style="width:120px;">
                        <h1>Campanhas</h1>
                        <p><a href="/index/campanhas">Campanhas</a></p>
                    </div>

                    <div class="box" style="width:120px;">
                        <h1>CONTATO</h1>
                        <p><a href="/index/fale-conosco">Fale Conosco</a></p>
                    </div>
                </footer>
                <!-- FIM  de Menus inferior --> 


                <!-- divisão parte da pagina --> 
                <div class="footer_bottom"></div>    

                <div id="blockend">
                    <div class="espaco">
                        <div style="float:left;text-align:left;">
                            <div  style="float:left;">
                                <p id="footer_gray">
                            </div>
                        </div>

                        <div class="espaco">
                            <div style="float:left;text-align:right;">
                                <div  style="float:left;">
                                    <p id="footer_gray">
                                        <!-- Fim  parte da pagina --> 



                                        <!-- INICIO - icone ir para o topo -->     
                                </div>
                            </div>

                            <div style="float:right;text-align:right;">
                                <div  style="float:left;">
                                    <p id="footer_gray"><a id="topo"><img src="/images/subir.png"> ir para o topo</a></p>
                                    <p style="margin-top:10px;"> Simova - © Copyright 2013</p>
                                </div>
                            </div>           
                        </div>
                    </div>

                    <!-- Fim - icone ir para o topo --> 

                </div>        
                </body>
                </html>

