<ul class="pager offset10">
    <li class="previous">
        <a href="/admin/cartao/consulta-cartao"><i class="icon-arrow-left"></i><strong>Voltar</strong></a>
    </li>
</ul>
<fieldset>
    <legend>Registro e Aprazamento de vacinas</legend>

    <?php echo $this->flashMessenger() ?>

    <div style="margin-bottom: 18px;" class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Dados do Paciente</a></li>
            <li class=""><a data-toggle="tab" href="#tab2">Registrar Vacinas</a></li>
            <li class=""><a data-toggle="tab" href="#tab3">Aprazar Vacinas</a></li>
        </ul>
        <form class="form-horizontal" method="post">
            <div class="tab-content">
                <div id="tab1" class="tab-pane active">

                    <!--INICIO DO PRIMEIRO MENU-->
                    <div class="span4">
                        <table class="table table-bordered">

                            <tbody  style="font-size: 13px;">
                                <tr class="info">
                                    <td>Código do Paciente:</td>
                                    <td><?php echo $this->paciente['cod_pessoa'] ?></td>
                                </tr>
                                <tr>
                                    <td>Nome do Paciente:</td>
                                    <td><?php echo $this->paciente['nome'] ?></td>
                                </tr>
                                <tr class="info">
                                    <td>Nome da Mãe:</td>
                                    <td><?php echo $this->paciente['nome_mae'] ?></td>
                                </tr>
                                <tr>
                                    <td>Data de Nascimento:</td>
                                    <td><?php echo date('d-m-Y', strtotime($this->paciente['dt_nasc'])) ?></td>
                                </tr>
                                <tr class="info">
                                    <td>Sexo:</td>
                                    <td><?php echo $this->paciente['sexo'] == 'M' ? 'Masculino' : 'Feminino' ?></td>
                                </tr>
                                <tr>
                                    <td>Telefone Celular:</td>
                                    <td><?php echo $this->paciente['num_tel'] ?></td>
                                </tr>
                                <tr class="info">
                                    <td>E-mail:</td>
                                    <td><?php echo $this->paciente['email'] ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div> <!--FIM DO PRIMEIRO MENU-->

                <div id="tab2" class="tab-pane">

                    <!--INICIO DO SEGUNDO MENU-->
                    <div class="rows-fluid">
                        <div class="span6"> 
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Data da Aplicação:</label>
                                <div class="controls">
                                    <?php echo $this->form->dt_vac_aplicada ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Número da Dose:</label>
                                <div class="controls">
                                    <?php echo $this->form->dose ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Unidade de Saúde:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_un_saude ?>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Nome da Vacina:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_vacina ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Lote da Vacina:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_lote ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Matricula do Responsável:</label>
                                <div class="controls">
                                    <?php echo $this->form->matricula ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Campanha:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_campanha ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!--FIM DO SEGUNDO MENU-->

                <div id="tab3" class="tab-pane">

                    <!--INICIO DO TERCEIRO MENU-->
                    <div class="rows-fluid">
                        <div class="span6"> 
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Data da Aplicação:</label>
                                <div class="controls">
                                    <?php echo $this->form->dt_aprazada ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Número da Dose:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_dose ?>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Unidade de Saúde:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_un_saude_apraz ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Nome da Vacina:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_vacina_apraz ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rows-fluid">
                        <div class="span12">
                            <div class="form-actions">
                                <div class="control-group">
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                    <button class="btn btn-primary" type="reset">Limpar</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div> <!--FIM DO TERCEIRO MENU-->
            </div>
        </form>
    </div>
</fieldset>











