<form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
    <div class="control-group">
        <label class="control-label">Insira o arquivo de importação:</label>
        <div class="controls">
            <input type="file" name="import">
        </div>
    </div>
    <div class="control-group">
        <div class="form-actions">
            <button class="btn btn-primary" type="submit" name="btn-import">Importar</button>
        </div>
    </div>
</form>