<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<ul class="pager offset10">
    <li class="previous">
        <a href="/admin/relatorio/vacina-aplicada"><i class="icon-arrow-left"></i><strong>Voltar</strong></a>
    </li>

</ul>
<fieldset>
    <legend>Relatório de Vacinas Aplicadas</legend>
    <?php echo $this->flashMessenger() ?>

    <table class="table table-bordered table-condensed " style="font-size: 13px;"> <!--INÍCIO DO CABEÇALHO-->
        <thead  style="font-size: 15px;">
            <tr>
                <th colspan="7" style="background-color: #08c; color: #FFFFFF; font-size: 20px;text-align: center;">Dados do Relatório</th>
            </tr>
            <tr>
                <th style="background-color: #08c; color: #FFFFFF;width: 180px;">Data inicial:&nbsp;</th>
                <th colspan="6"> 10/01/2013</th>
            </tr>
            <tr>
                <th style="background-color: #08c; color: #FFFFFF">Data Final:&nbsp;</th>
                <th colspan="6">10/03/2013</th>
            </tr>

            <tr>
                <th style="background-color: #08c; color: #FFFFFF">Vacina:&nbsp;</th>
                <th colspan="6">Todas</th>
            </tr>
            <tr>
                <th style="background-color: #08c; color: #FFFFFF">Paciente:&nbsp;</th>
                <th colspan="6">Leonardo da Vinci</th>
            </tr>
            <tr>
                <th style="background-color: #08c; color: #FFFFFF">Unidade de Saúde:&nbsp;</th>
                <th colspan="6">Centro de Saúde nº 02</th>
            </tr>
        </thead>
        <tr>
            <td colspan="6" style="background-color: #08c; color: #FFFFFF; height: 20px"></td>
        </tr>
        <tr>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;">Nome da vacina</td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;">Nome do paciente</td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;">Data de aplicação</td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;">Centro de Saúde</td>
        </tr>
        <tr>
            <td style="background-color: #FFFFFF; color: #000; font-size: 12px;text-align: center;">Triplice Viral</td>
            <td style="background-color: #FFFFFF; color: #000; font-size: 12px;text-align: center;">Leonardo da Vinci</td>
            <td style="background-color: #FFFFFF; color: #000; font-size: 12px;text-align: center;">10/01/2013</td>
            <td style="background-color: #FFFFFF; color: #000; font-size: 12px;text-align: center;">Centro de Saúde nº 02</td>
        </tr>
        <tr>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;">Triplice Viral</td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;">Leonardo da Vinci</td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
            <td style="background-color: #d9edf7; color: #000; font-size: 15px;text-align: center;"></td>
        </tr>
    </table> <!--FIM DO CABEÇALHO-->



</fieldset>













