<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<fieldset>
    <legend>Cadastrar Vacinas</legend>
    <?php
    if ($this->mensagem):
        ?>
        <div class="alert <?php echo $this->mensagem['type'] ?>"><?php echo $this->mensagem['mensagem'] ?></div>
        <?php
    endif;
    ?>

    <div style="margin-bottom: 18px;" class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Dados Principais</a></li>

        </ul>
       
            <div class="tab-content">
                <div id="tab1" class="tab-pane active">  <!--INICIO DA PRIMEIRA ABA-MENU-->


                     <form class="form-horizontal" method="post">

                       

                        <div class="rows-fluid">
                            <div class="span6">
                                <div class="control-group">
                                    <div class="control-group">
                                        <label for="inputEmail" class="control-label">Nome da Vacina:</label>
                                        <div class="controls">
                                            <input type="text" placeholder="Text input">
                                        </div>
                                    </div>
                                    <label for="inputEmail" class="control-label">Lote da Vacina:</label>
                                    <div class="controls">
                                        <input type="text" placeholder="Text input">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Fabricante:</label>
                                    <div class="controls">
                                        <input type="text" placeholder="Text input">
                                    </div>
                                </div>

                            </div>
                            <div class="span6">
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Data de Fabricação:</label>
                                    <div class="controls">
                                        <input type="text" placeholder="Text input">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Data de Vencimento:</label>
                                    <div class="controls">
                                        <input type="text" placeholder="Text input">
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Quantidade:</label>
                                    <div class="controls">
                                        <input type="text" placeholder="Text input">
                                    </div>
                                </div>

                            </div>
                            <div class="rows-fluid">
                                <div class="span12">
                                    <div class="form-actions">
                                        <div class="control-group">
                                            <button class="btn btn-primary" type="submit">Salvar</button>
                                            <button class="btn btn-primary" type="reset">Limpar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                    


                    </form>
                </div> <!--FIM DA PRIMEIRA ABA-MENU-->
            </div>
    </div>
</fieldset>











