<style type="text/css">

    h1#aa{
        background-color: #ffcc99;
        text-align: center;
        font-size: 20pt;
        width: 550pt;
        margin: 10px 0 30px 5px;

    }
    li a:hover{
        color: #CB0101;

    }
    li a:active{
        border-style: none;
    }

    .tabbable{
        height: auto;
    }

    div #content{
        width: 745px;
        height:700px;
        margin: 0 0 0 355px;
        padding: 40px;
        background: #fff;
    }



</style>



<div class="span9">
    <h1 id="aa">Cadastrar Vacinas</h1>


    <form class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="inputEmail">Nome da Vacina:</label>
            <div class="controls">
                <input type="text" placeholder="Text input">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Lote da Vacina:</label>
            <div class="controls">
                <input type="text" placeholder="Text input">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Fabricante:</label>
            <div class="controls">
                <input type="text" placeholder="Text input">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Data de Fabricação:</label>
            <div class="controls">
                <input type="text" placeholder="Text input">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Data de Vencimento:</label>
            <div class="controls">
                <input type="text" placeholder="Text input">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Quantidade:</label>
            <div class="controls">
                <input type="text" placeholder="Text input">
            </div>
        </div>
        <div class="control-group">

            <div class="controls">
                <button class="btn btn-info" type="submit">Salvar</button>
                <button class="btn btn-info" type="reset">Limpar</button>

            </div>
        </div>

    </form>

</div>
