<style type="text/css">

    h1#aa{
        background-color: #ffcc99;
        text-align: center;
        font-size: 20pt;
        width: 550pt;
        margin: 10px 0 30px 5px;

    }
    li a:hover{
        color: #CB0101;

    }
    li a:active{
        border-style: none;
    }

    .tabbable{
        height: auto;
    }

    div #content{
        width: 745px;
        height:700px;
        margin: 0 0 0 355px;
        padding: 40px;
        background: #fff;
    }



</style>



<div class="span9">
    <h1 id="aa">Consultar Vacinas</h1>


    

</div>
