<?php echo $this->modal ?>
<?php echo $this->flashMessenger(); ?>
<fieldset>
    <legend>Consultar Vacinas</legend>
    <form class="form-inline" method="post" action="">
        <select name="tipoConsulta">
            <option value="">Selecione a opção</option>
            <option value="nome_vacina">Nome da vacina</option>
            <option value="cod_vacina">Código da vacina</option>
            <option value="">Todos</option>
        </select>
        <div class="input-append">
            <input class="input-large" name="search" id="appendedInputButton" type="text">
            <button type="submit" class="btn btn-info"><i class="icon-search icon-white"></i>Pesquisar</button>
        </div>
    </form>

    <!--ABAIXO APARECERÁ A LISTA COM OS RESULTADOS DA CONSULTA-->

    <!--PAGINAÇÃO DAS TABELAS DA PESQUISA-->
    <?php if (count($this->vacinas)): ?>
        <table class="table table-bordered table-striped" style="font-size: 13px;">
            <div class="alert alert-info">Resultado(s) da(s) consulta(s) para: <strong><?php echo $this->request['search'] ?></strong></div>
            <thead style="background-color: #08c; color: #FFFFFF">
                <tr>
                   <!-- <th>Código da Vacina</th>-->
                    <th>Nome da Vacina</th>
                    <th>Numero do Lote</th>
                    <th>Data de Fabricação</th>
                    <th>Data de Vencimento</th>
                    <th width="75">Função</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->vacinas as $vacinas): ?>
                    <tr>
                       <!--<td><?php echo $vacinas->cod_vacina ?></td>-->
                        <td><?php echo $vacinas->nome_vacina ?></td>
                        <td><?php echo $vacinas->num_lote ?></td>
                        <td><?php echo date('d-m-Y', strtotime($vacinas->dt_fabric)) ?></td>
                        <td><?php echo date('d-m-Y', strtotime($vacinas->dt_venc)) ?></td>
                        <td>
                            <a href="/admin/vacina/alterar-vacina/cod_vacina/<?php echo $vacinas->cod_vacina ?>" title="Alterar" class="btn btn-primary btn btn-mini"><i class="icon-pencil icon-white"></i></a>
                            <a href="/admin/vacina/excluir-vacina/cod_lote/<?php echo $vacinas->cod_lote ?>/cod_vacina/<?php echo $vacinas->cod_vacina ?>" title="Excluir" class="btn btn-danger btn btn-mini confirm"><i class="icon-trash icon-white"></i></a>&nbsp;
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="pagination pagination-centered">
            <ul>
                <!--TABELA COM OS DADOS DA PESQUISA-->
                <li><a href="<?php echo $this->pagination->previous ?>">Anterior</a></li>
                <?php echo $this->pagination->pages ?>
                <li><a href="<?php echo $this->pagination->next ?>">Proximo</a></li>
            </ul>
        </div>
    <?php endif; ?>
</fieldset>