<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<fieldset>
    <legend>Alterar Perfil</legend>
    <?php
    if ($this->mensagem):
        ?>
        <div class="alert <?php echo $this->mensagem['type'] ?>"><?php echo $this->mensagem['mensagem'] ?></div>
        <?php
    endif;
    ?>

    <div style="margin-bottom: 18px;" class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Dados Principais</a></li>

        </ul>
        <form action="" class="form-horizontal" method="post">
            <div class="tab-content">
                <div id="tab1" class="tab-pane active">


                    <div id="tab1" class="tab-pane">

                        <!--INICIO DO PRIMEIRO FORM-->

                        <div class="rows-fluid">
                            <div class="span6">
                                <div class="control-group">

                                    <label for="inputEmail" class="control-label">Usuário:</label>
                                    <div class="controls">
                                        <?php echo $this->form->Login->nome_login ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Telefone Celular:</label>
                                    <div class="controls">
                                        <?php echo $this->form->Telefone->num_tel1 ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Telefone Residencial:</label>
                                    <div class="controls">
                                        <?php echo $this->form->Telefone->num_tel2 ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">E-mail:</label>
                                    <div class="controls">
                                        <?php echo $this->form->email ?>
                                    </div>
                                </div>

                            </div>
                            <div class="span6">

                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Senha:</label>
                                    <div class="controls">
                                        <?php echo $this->form->Login->senha_login ?>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label">Confirmar-Senha:</label>
                                    <div class="controls">
                                        <?php echo $this->form->Login->senha_login ?>
                                    </div>
                                </div>
                            </div>
                            <div class="rows-fluid">
                                <div class="span12">
                                    <div class="form-actions">
                                        <div class="control-group">
                                            <button class="btn btn-primary" type="submit">Salvar</button>
                                            <button class="btn btn-primary" type="reset">Limpar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!--FIM DO PRIMEIRO MENU-->
                    </div>
                </div>
            </div>
        </form>
    </div>
</fieldset>











