<form method="POST" name="cadastro-pessoa" id="cadastro-pessoa">
    <div class="control-group">
        <label class="control-label">Nome:</label>
        <div class="controls">
            <?php echo $this->form->NOME ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">CPF:</label>
        <div class="controls">
            <?php echo $this->form->CPF ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Nome da Mãe:</label>
        <div class="controls">
            <?php echo $this->form->NOME_MAE ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Nome do Pai:</label>
        <div class="controls">
            <?php echo $this->form->NOME_PAI ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Nome do Pai:</label>
        <div class="controls">
            <?php echo $this->form->NOME_PAI ?>
        </div>
    </div>
</form>

<?php

    //echo $this->form->Endereco;
?>
