
<!--CHAMADA PARA O ARQUIVO JQUERY-->
<script type="text/javascript" src="/administrator/js/pessoa.js"></script>
<?php echo $this->modal ?>

<!-- METODO USADO PARA EXIBIR MENSAGENS DO SISTEMA-->
<?php echo $this->flashMessenger() ?> 

<fieldset>
    <legend>Cadastrar Funcionário</legend>

    <div style="margin-bottom: 18px;" class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Dados Principais</a></li>
            <li class=""><a data-toggle="tab" href="#tab2">Endereço</a></li>
            <li class=""><a data-toggle="tab" href="#tab3">Dados Complementares</a></li>
        </ul>
        <form class="form-horizontal" method="post">
            <div class="tab-content">

                <div id="tab1" class="tab-pane active"> <!--INICIO DA ABA DADOS PRINCIPAIS-->

                    <div class="rows-fluid">  
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Nome Completo:</label>
                                <div class="controls">
                                    <?php echo $this->form->nome ?> <!--ESSE CODIGO EXIBE O-->
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Nome do Pai:</label>
                                <div class="controls">
                                    <?php echo $this->form->nome_pai ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Nome da Mãe:</label>
                                <div class="controls">
                                    <?php echo $this->form->nome_mae ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Data de Nascimento:</label>
                                <div class="controls">
                                    <?php echo $this->form->dt_nasc ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">RG Nº:</label>
                                <div class="controls">
                                    <?php echo $this->form->rg ?>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">CPF Nº:</label>
                                <div class="controls">
                                    <?php echo $this->form->cpf ?>
                                    <div id="cpf-error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Nº Registro de Nascimento:</label>
                                <div class="controls">
                                    <?php echo $this->form->registro_nasc ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Estado Civil:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_estado_civil ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Sexo:</label>
                                <div class="controls">
                                    <?php echo $this->form->sexo ?>
                                </div>
                            </div>


                        </div>

                    </div>
                    <!--<div class="rows-fluid">
                        <div class="span12">
                            <div class="form-actions">
                                <div class="control-group">
                                    <a class="btn btn-primary" href="#tab2" data-toggle="tab">Continuar <i class="icon-forward icon-white"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>-->

                </div> <!--FIM DA ABA DADOS PRINCIPAIS-->

                <div id="tab2" class="tab-pane"> <!--INICIO DA ABA ENDEREÇO-->

                    <div class="rows-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Endereço:</label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->endereco ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Número:</label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->numero ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Complemento: </label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->complemento ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Bairro:</label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->bairro ?>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">CEP:</label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->cep ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> UF:</label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->cod_uf ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Cidade:</label>
                                <div class="controls">
                                    <?php echo $this->form->Endereco->cod_cid ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- <div class="rows-fluid"> 
                         <div class="span12">
                             <div class="form-actions">
                                 <div class="control-group">
                                     <a class="btn btn-primary" href="#tab1" data-toggle="tab">Voltar <i class="icon-backward icon-white"></i></a>
                                     <a class="btn btn-primary" href="#tab3" data-toggle="tab">Continuar <i class="icon-forward icon-white"></i></a>
                                 </div>
                             </div>
                         </div>
                     </div>-->
                </div> <!--FIM DA ABA ENDEREÇO-->

                <div id="tab3" class="tab-pane">  <!--INICIO DA ABA DADOS COMPLEMENTARES-->

                    <div class="rows-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <div class="control-group">
                                    <label for="inputEmail" class="control-label"><b>*</b> Matrícula:</label>
                                    <div class="controls">
                                        <?php echo $this->form->Funcionario->matricula ?>
                                    </div>
                                </div>
<!--                                <label for="inputEmail" class="control-label">Cargo:</label>
                                <div class="controls">
                                    <?php //echo $this->form->Funcionario->cod_cargo ?>
                                </div>-->
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Função:</label>
                                <div class="controls">
                                    <?php echo $this->form->Funcionario->cod_funcao ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Lotação:</label>
                                <div class="controls">
                                    <input type="text" placeholder="">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Unidade de Saúde:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_un_saude ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Status:</label>
                                <div class="controls">
                                    <?php echo $this->form->Status->cod_status ?>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Telefone residêncial:</label>
                                <div class="controls">
                                    <?php echo $this->form->telefone_residencial ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Telefone celular:</label>
                                <div class="controls">
                                    <?php echo $this->form->telefone_celular ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">E-mail:</label>
                                <div class="controls">
                                    <input id="email" class="input-xlarge" type="email" value="" name="email">
                                    <?php //echo $this->form->email ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Perfil:</label>
                                <div class="controls">
                                    <?php echo $this->form->cod_perfil ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Usuário:</label>
                                <div class="controls">
                                    <?php echo $this->form->Login->nome_login ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Senha:</label>
                                <div class="controls">
                                    <?php echo $this->form->Login->senha_login ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label"><b>*</b> Confirmar-Senha:</label>
                                <div class="controls">
                                    <?php echo $this->form->Login->senha_login ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="rows-fluid">
                        <div class="span12">
                            <div class="form-actions">
                                <div class="control-group">
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                    <button class="btn btn-primary" type="reset">Limpar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!--FIM DA ABA DADOS COMPLEMENTARES-->
            </div>
        </form>
    </div>
    <div>
        <strong>(*) Campos obrigatórios.</strong>
    </div>
</fieldset>
