<h3>Cadastro de Pessoa</h3>
<div class="span9">
    <form class="form form-horizontal" method="POST" name="cadastro-pessoa" id="cadastro-pessoa">
        <fieldset>
            <legend>Dados Pessoais</legend>
            <div class="control-group">
                <?php echo $this->form->Nome ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->CPF ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->RG ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Sexo ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->DT_Nasc ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Registro ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Estado_Civil ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->TB_Unidade_Saude_Cod_Un_Saude ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Cod_Perfil ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Dados de Localização</legend>
            <div class="control-group">
                <?php echo $this->form->Endereco->COD_CID ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Endereco->ENDERECO ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Endereco->CEP ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Endereco->BAIRRO ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Endereco->NUMERO ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->Endereco->COMPLEMENTO ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Dados de Familiares</legend>
            <div class="control-group">
                <?php echo $this->form->NOME_MAE ?>
            </div>
            <div class="control-group">
                <?php echo $this->form->NOME_PAI ?>
            </div>
        </fieldset>
        <div class="form-actions">
            <div class="btn-group pull-right">
                <button type="submit" class="btn btn-primary">Salvar</button>
                <button type="reset" class="btn">Limpar</button>
                <a href="/admin/pessoa">
                    <button type="button" class="btn">Cancelar</button>
                </a>
            </div>
        </div>
    </form>
</div>