<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<?php
echo $this->modal;
echo $this->flashMessenger();
?>

<fieldset>
    <legend>Consultar Funcionário</legend>

    <form class="form-inline" method="post" action="">
        <select name="tipoConsulta">
            <option value="">Selecione a opção</option>
            <option value="nome">Nome</option>
            <option value="matricula">Matricula</option>
            <option value="">Todos</option>
        </select>
        <div class="input-append">
            <input class="input-large" name="search" id="appendedInputButton" type="text">
            <button type="submit" class="btn btn-info"><i class="icon-search icon-white"></i>&nbsp;Pesquisar</button>
        </div>
    </form>

    <!--ABAIXO APARECERÁ A LISTA COM OS RESULTADOS DA CONSULTA-->

    <!--PAGINAÇÃO DAS TABELAS DA PESQUISA-->
    <?php if (count($this->listFuncionarios) > 0): ?>
        <table id="table-paginator" class="table table-bordered table-striped"  style="font-size: 13px;">
            <div class="alert alert-info">Resultado(s) da(s) consulta(s) para: <strong><?php echo $this->request['search'] ?></strong></div>
            <thead style="background-color: #08c; color: #FFFFFF">
                <tr>
                    <th>Código</th>
                    <th>Usuário</th>
                    <th>Nome Completo</th>
                    <th>Matrícula Nº</th>
                    <th>Status</th>
                    <th>Função</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->listFuncionarios as $funcionarios): ?>
                    <tr>
                        <td><?php echo $funcionarios->cod_pessoa ?></td>
                        <td><?php echo $funcionarios->nome_login ?></td>
                        <td><?php echo $funcionarios->nome ?></td>
                        <td><?php echo $funcionarios->matricula ?></td>
                        <td><?php echo $funcionarios->cod_status == 1 ? 'Ativo' : 'Inativo' ?></td>
                        <td>
                            <a href="/admin/pessoa/editar-funcionario/cod_pessoa/<?php echo $funcionarios->cod_pessoa ?>" title="Alterar" class="btn btn-primary btn btn-mini"><i class="icon-edit icon-white"></i></a>
                            <a href="/admin/pessoa/excluir-funcionario/cod_pessoa/<?php echo $funcionarios->cod_pessoa ?>" title="Excluir" class="btn btn-danger btn btn-mini confirm"><i class="icon-trash icon-white"></i></a>&nbsp;
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="pagination pagination-centered">
            <ul>
                <!--TABELA COM OS DADOS DA PESQUISA-->
                <li><a href="<?php echo $this->pagination->previous ?>">Anterior</a></li>
                <?php echo $this->pagination->pages ?>
                <li><a href="<?php echo $this->pagination->next ?>">Proximo</a></li>
            </ul>
        </div>
    <?php endif; ?>
</fieldset>