<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<?php
echo $this->modal;
echo $this->flashMessenger();
?>

<legend>Consultar Paciente</legend>
<form class="form-inline" action="" method="post">
    <select name="tipoConsulta">
        <option value="">Selecione a opção</option>
        <option value="nome">Nome</option>
        <option value="nome">Registro Nascimento</option>
        <option value="rg">RG</option>
        <option value="cpf">CPF</option>
        <option value="">Todos</option>
    </select>
    <div class="input-append">
        <input class="input-xlarge" name="search" id="appendedInputButton" type="text">
        <button class="btn btn-info" type="submit"><i class="icon-search icon-white"></i>&nbsp;Pesquisar</button>
    </div>
</form>

<!--ABAIXO APARECERÁ A LISTA COM OS RESULTADOS DA CONSULTA-->

<?php if (count($this->listPacientes)): ?>
    <div class="alert alert-info">Resultado(s) da(s) consulta(s) para: <strong><?php echo $this->request['search'] ?></strong></div>
    <table class="table table-bordered table-striped"  style="font-size: 13px;">
        <thead style="background-color: #08c; color: #FFFFFF">
            <tr>
               <!-- <th>Código</th>-->
                <th>Nome Completo</th>
                <th>Registro Nascimento</th>
                <th>RG Nº</th>
                <th>CPF Nº</th>
                <th width="100">Função</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->listPacientes as $paciente): ?>
                <tr>
                   <!-- <td><?php echo $paciente->cod_pac ?></td>-->
                    <td><?php echo $paciente->nome ?></td>
                    <td><?php echo $paciente->rg ?></td>
                    <td><?php echo $paciente->rg ?></td>
                    <td><?php echo $paciente->cpf ?></td>
                    <td>
                        <a href="/admin/pessoa/visualisa-cadastro/cod_pessoa/<?php echo $funcionarios->cod_pessoa ?>" title="Visualisar cadastro" class="btn btn-warning btn btn-mini"><i class="icon-eye-open icon-white"></i></a>
                        <a href="/admin/pessoa/editar-paciente/cod_pessoa/<?php echo $paciente->cod_pessoa ?>" 
                           title="Alterar cadastro" class="btn btn-info btn-mini">
                            <i class="icon-edit icon-white"></i>
                        </a>
                        <a href="/admin/pessoa/excluir-paciente/cod_pessoa/<?php echo $paciente->cod_pessoa ?>" 
                           title="Excluir" class="btn btn-danger btn-mini confirm">
                            <i class="icon-trash icon-white"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="pagination pagination-centered">
        <ul>
            <!--TABELA COM OS DADOS DA PESQUISA-->
            <li><a href="<?php echo $this->pagination->previous ?>">Anterior</a></li>
            <?php echo $this->pagination->pages ?>
            <li><a href="<?php echo $this->pagination->next ?>">Proximo</a></li>
        </ul>
    </div>
    <?php
endif;
?>