<script type="text/javascript" src="/admin/js/pessoa.js"></script>

<?php if (count($this->listPacientes)<=0): ?>
    <div class="alert alert-warning">Nenhum resultado encontrado</div>
<?php endif; ?>

<legend>Consultar Pacientes</legend>
<form class="form-inline" action="" method="post">
    <select name="tipoConsulta">
        <option value="">Selecione a opção</option>
        <option value="nome">Nome</option>
        <option value="rg">RG</option>
        <option value="cpf">CPF</option>
        <option value="">Todos</option>
    </select>
    <div class="input-append">
        <input class="input-xlarge" name="search" id="appendedInputButton" type="text">
        <button class="btn btn-info" type="submit"><i class="icon-search icon-white"></i>Pesquisar</button>
    </div>
</form>

<!--ABAIXO APARECERÁ A LISTA COM OS RESULTADOS DA CONSULTA-->

<?php if (count($this->listPacientes)): ?>
<div class="alert alert-info">Resultado(s) da(s) consulta(s) para: <strong><?php echo $this->request['search'] ?></strong></div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome Completo</th>
                <th>RG Nº</th>
                <th>CPF Nº</th>
                <th width="75">Função</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->listPacientes as $paciente): ?>
                <tr>
                    <td><?php echo $paciente->cod_pac ?></td>
                    <td><?php echo $paciente->nome ?></td>
                    <td><?php echo $paciente->rg ?></td>
                    <td><?php echo $paciente->cpf ?></td>
                    <td>
                        <a href="/admin/pessoa/editar-funcionario/cod_pessoa/<?php echo $funcionarios->cod_pessoa ?>" title="Alterar" class="btn btn-primary btn btn-mini"><i class="icon-pencil icon-white"></i></a>
                        <a href="/admin/pessoa/excluir-funcionario/cod_pessoa/<?php echo $funcionarios->cod_pessoa ?>" title="Excluir" class="btn btn-danger btn btn-mini confirm"><i class="icon-trash icon-white"></i></a>&nbsp;
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php
endif;
?>