<ul class="pager offset10">
    <li class="previous">
        <a href="/admin/pessoa/consulta-paciente"><i class="icon-arrow-left"></i><strong>Voltar</strong></a>
    </li>

</ul>

<fieldset>
    <legend>Visualisar Cadastro do Paciente</legend> 

    <div class="row-fluid">

        <div  class ="span10">
           

                <table class="table table-bordered table-condensed ">

                   <!-- <caption style="font-size: 20px;font-weight: bold;">Dados Cadastrais</caption> -->
                    <tbody  style="font-size: 13px;">
                        <tr>
                            <td style="background-color: #08c; color: #FFFFFF;font-size: 20px;font-weight: bold;text-align: center;" colspan="2">Dados Principais</td>
                        </tr>
                       <!-- <tr class="info">
                            <td  style="font-size: 15px;font-weight: bold;width: 220px;background-color: #08c; color: #FFFFFF;">Código do Funcionário:</td>
                            <td><?php echo $this->pessoa->cod_pessoa?></td>
                        </tr> -->
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Nome do Funcionário:</td>
                            <td><?php echo $this->pessoa->nome?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Nome da Mãe:</td>
                            <td><?php echo $this->pessoa->nome_mae?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Nome do Pai:</td>
                            <td><?php echo $this->pessoa->nome_pai?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Data de Nascimento:</td>
                            <td><?php echo Simova_Date::dateToView($this->pessoa->dt_nasc) ?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">RG Nº:</td>
                            <td><?php echo $this->pessoa->rg?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">CPF Nº:</td>
                            <td><?php echo $this->pessoa->cpf?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Registro de Nascimento Nº:</td>
                            <td><?php echo $this->pessoa->registro_nasc?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Estado civil:</td>
                            <td><?php echo $this->pessoa->nome_estado_civil?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Sexo:</td>
                            <td><?php echo $this->pessoa->sexo?></td>
                        </tr>
                        <tr>
                            <td style="background-color: #08c; color: #FFFFFF;font-size: 20px;font-weight: bold;text-align: center;" colspan="2">Endereço</td>
                        </tr>
                        <tr class="info">
                            <td  style="font-size: 15px;font-weight: bold;width: 220px;background-color: #08c; color: #FFFFFF;">Endereço:</td>
                            <td><?php echo $this->pessoa->endereco?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Número:</td>
                            <td><?php echo $this->pessoa->numero?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Complemento:</td>
                            <td><?php echo $this->pessoa->complemento?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Bairro:</td>
                            <td><?php echo $this->pessoa->bairro?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">CEP:</td>
                            <td><?php echo $this->pessoa->cep?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">UF:</td>
                            <td><?php echo $this->pessoa->sigla_uf?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Cidade:</td>
                            <td><?php echo $this->pessoa->nome_uf?></td>
                        </tr>
                        <tr>
                            <td style="background-color: #08c; color: #FFFFFF;font-size: 20px;font-weight: bold;text-align: center;" colspan="2">Dados Complementares</td>
                        </tr>
                                                
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Status:</td>
                            <td><?php echo $this->pessoa->nome_status?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Telefone Residencial:</td>
                            <td><?php echo $this->pessoa->telefone_residencial?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Telefone Celular:</td>
                            <td><?php echo $this->pessoa->telefone_celular?></td>
                        </tr>

                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">E-mail:</td>
                            <td><?php echo $this->pessoa->email?></td>
                        </tr>
                        <tr>
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Perfil:</td>
                            <td><?php echo $this->pessoa->nome_perfil?></td>
                        </tr>
                        <tr class="info">
                            <td style="font-size: 15px;font-weight: bold;background-color: #08c; color: #FFFFFF;">Usuário:</td>
                            <td><?php echo $this->pessoa->nome_login?></td>
                        </tr>
                        <tr>
                            <td style="background-color: #08c; color: #FFFFFF;height: 20px" colspan="2"></td>
                        </tr>
                    

                    </tbody>
                </table>
            </div>

        </div>
    