<ul class="pager offset10">
    <li class="previous">
        <a href="/admin/cartao/consulta-cartao"><i class="icon-arrow-left"></i><strong>Voltar</strong></a>
    </li>

</ul>

<table class="table table-bordered">

    <tbody  style="font-size: 13px;">
        <tr class="info">
            <td>Código do Paciente:</td>
            <td>12</td>
        </tr>
        <tr>
            <td>Nome do Paciente:</td>
            <td>José da Silva</td>
        </tr>
        <tr class="info">
            <td>Nome da Mãe:</td>
            <td>Maria da Silva</td>
        </tr>
        <tr>
            <td>Data de Nascimento:</td>
            <td>06/10/1989</td>
        </tr>
        <tr class="info">
            <td>Sexo:</td>
            <td>Masculino</td>
        </tr>
        <tr>
            <td>Telefone Celular:</td>
            <td>(61)9152-8547</td>
        </tr>
        <tr class="info">
            <td>E-mail:</td>
            <td>jose_silva@gmail.com</td>
        </tr>
    </tbody>
</table>