<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<fieldset>
    <legend>Cadastrar Unidades de Saúde</legend>
    <?php
    if ($this->mensagem):
        ?>
        <div class="alert <?php echo $this->mensagem['type'] ?>"><?php echo $this->mensagem['mensagem'] ?></div>
        <?php
    endif;
    ?>

    <div style="margin-bottom: 18px;" class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Dados Principais</a></li>
            <li class=""><a data-toggle="tab" href="#tab2">Endereço</a></li>

        </ul>
        <form class="form-horizontal" method="post">
            <div class="tab-content">
                <div id="tab1" class="tab-pane active">

                    <!--INICIO DO PRIMEIRO MENU-->

                    <div class="rows-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Nome da Unidade:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Número da Unidade:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Telefone:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">E-mail:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>

                        </div>

                    </div>
                    <!--  <div class="rows-fluid">
                          <div class="span12">
                              <div class="form-actions">
                                  <div class="control-group">
                                      <a class="btn btn-primary" href="#tab2" data-toggle="tab">Continuar <i class="icon-forward icon-white"></i></a>
                                  </div>
                              </div>
                          </div>
                      </div>-->

                </div> <!--FIM DO PRIMEIRO MENU-->

                <div id="tab2" class="tab-pane">

                    <!--INICIO DO SEGUNDO MENU-->

                    <div class="rows-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Rua:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Complemento: </label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Número:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Bairro:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">CEP:</label>
                                <div class="controls">
                                    <input type="text" placeholder="Text input">
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">UF:</label>
                                <div class="controls">
                                    <select>
                                        <option>Selecione a opção</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Cidade:</label>
                                <div class="controls">
                                    <select>
                                        <option>Selecione a opção</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rows-fluid">
                        <div class="span12">
                            <div class="form-actions">
                                <div class="control-group">
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                    <button class="btn btn-primary" type="reset">Limpar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!--FIM DO SEGUNDO MENU-->
            </div>
        </form>
    </div>
</fieldset>

