<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Painel Administrativo</title>
        <link href="/assets/css/jquery.stepy.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/css/blue.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/css/style.css" media="screen" rel="stylesheet" type="text/css">
        <!-- Favicon -->
        <link rel="shortcut icon" href="/favicon.ico">

        <!--[if lte IE 8]>
            <link rel="stylesheet" href="/css/ie.css" />
            <script src="/js/ie/html5.js"></script>
                        <script src="/js/ie/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>

        <div id="maincontainer" class="clearfix">
            <!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <div id="store-logomarca">
                                <a class="brand" href="/admin"><i class="icon-home icon-white"></i> <span id="store-name">Painel</span></a>
                            </div>
                            <ul class="nav user_menu pull-right">
                                <li class="hidden-phone hidden-tablet">
                                    <div class="nb_boxes clearfix">
                                        <a data-toggle="modal" data-backdrop="static" href="#" class="label ttip_b" title="Seu plano no Comércio Daqui">Conta Grátis <i class="splashy-shield"></i></a>
                                    </div>
                                </li>
                                <li class="divider-vertical hidden-phone hidden-tablet"></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="/img/user_avatar.png" alt="" class="user_avatar" /> 
                                        <ul class="dropdown-menu">
                                            <li><a href="/admin/perfil/editar">Editar detalhe da conta</a></li>
                                            <li><a href="/admin/perfil/upload-image">Alterar logo</a></li>
                                            <li><a href="/admin/perfil/alterar-senha">Alterar senha</a></li>
                                            <li class="divider"></li>
                                            <li><a href="/admin/auth/logout">Sair</a></li>
                                        </ul>
                                </li>
                            </ul>
                            <a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
                                <span class="icon-align-justify icon-white"></span>
                            </a>
                            <nav>
                                <div class="nav-collapse">
                                    <ul class="nav">
                                        <li class="dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" href="/#"> 
                                                <i class="icon-th icon-white"></i>
                                                Catálogo
                                                <b class="caret"></b>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a href="/admin/produtos/catalogo">Produtos</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </header>

            <!-- main content -->
            <div id="contentwrapper">
                <div class="main_content">
                    <nav>
<!--                        <div id="jCrumbs" class="breadCrumb module">
                            <ul>
                                <li>
                                    <a href="/admin"><i class="icon-home"></i></a>
                                </li>
                                <li>
                                </li>
                                <style>
                                    .icon-separator{
                                        background: url("/img/separator.png") no-repeat scroll 100% 0 transparent;
                                        padding-bottom: 3px;
                                    }
                                </style>
                            </ul>
                        </div>-->
                    </nav>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>

            <!-- sidebar -->
            <a href="javascript:void(0)" class="sidebar_switch on_switch ttip_r" title="Ocultar menu">Menu</a>
            <div class="sidebar">
                <div class="antiScroll">
                    <div class="antiscroll-inner">
                        <div class="antiscroll-content">
                            <div class="sidebar_inner">
                                <div id="side_accordion" class="accordion">
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a href="/admin/pessoa/cadastro" data-parent="#side_accordion" data-toggle="collapse" class="accordion-toggle">
                                                <i class="icon-user"></i> Usuários
                                            </a>
                                        </div>
                                        <div class="accordion-body collapse" id="collapseThree">
                                            <div class="accordion-inner">
                                                <ul class="nav nav-list">
                                                    <li><a href="/admin/perfil/editar">Detalhe da conta</a></li>
                                                    <li><a href="/admin/perfil/upload-image">Alterar logo</a></li>
                                                    <li><a href="/admin/perfil/alterar-senha">Alterar senha</a></li>
                                                </ul>

                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-group">
                                        <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a href="#collapseFour" data-parent="#side_accordion" 
                                                   data-toggle="collapse" class="accordion-toggle">
                                                    <i class="icon-globe"></i>
                                                    Meus Aplicativos
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="collapseFour">
                                                <div class="accordion-inner">
                                                    <ul class="nav nav-list elert alert-error">
                                                        <li><a href="/admin/mensagens/perguntas-clientes">Perguntas de Clientes (54)</a></li>
                                                    </ul>
                                                    <br />
                                                    <a class="btn btn-primary btn-small" style="color: #fff;" href="/admin/loja-owen">
                                                        <i class="icon icon-list icon-white"></i>
                                                        Aplicativos no Owen Store
                                                    </a>
                                                    <br />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="accordion-group">
                                            <div class="accordion-heading sdb_h_active">
                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#side_accordion" href="#collapse7">
                                                    <i class="icon-th"></i> Calculadora
                                                </a>
                                            </div>
                                            <div id="collapse7" class="accordion-body collapse in">
                                                <div class="accordion-inner">
                                                    <form id="calc" name="Calc">
                                                        <div class="formSep control-group input-append">
                                                            <input type="text" name="Input" style="width:130px"><button onclick="Calc.Input.value = ''" value="c" name="clear" class="btn" type="button"><i class="icon-remove"></i></button>
                                                        </div>
                                                        <div class="control-group">
                                                            <input type="button" onclick="Calc.Input.value += '7'" value="7" name="seven" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '8'" value="8" name="eight" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '9'" value="9" name="nine" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += ' / '" value="/" name="div" class="btn btn-large">
                                                        </div>
                                                        <div class="control-group">
                                                            <input type="button" onclick="Calc.Input.value += '4'" value="4" name="four" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '5'" value="5" name="five" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '6'" value="6" name="six" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += ' * '" value="x" name="times" class="btn btn-large">
                                                        </div>
                                                        <div class="control-group">
                                                            <input type="button" onclick="Calc.Input.value += '1'" value="1" name="one" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '2'" value="2" name="two" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '3'" value="3" name="three" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += ' - '" value="-" name="minus" class="btn btn-large">
                                                        </div>
                                                        <div class="formSep control-group">
                                                            <input type="button" onclick="Calc.Input.value += '.'" value="." name="dot" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += '0'" value="0" name="zero" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value = Math.round(eval(Calc.Input.value) * 1000) / 1000" value="=" name="DoIt" class="btn btn-large">
                                                            <input type="button" onclick="Calc.Input.value += ' + '" value="+" name="plus" class="btn btn-large">
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="push"></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
    <script type="text/javascript" src="/assets/js/jquery.js"></script>
    <script type="text/javascript" src="/assets/js/gebo_common.js"></script>
    <script type="text/javascript" src="/assets/js/gebo_dashboard.js"></script>
</html>

