<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

        
        Nome       : Modulo Administrativo Simova
        Versão    : 1.0
        

--> 
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>Painel Administrativo</title>

        <link href="/assets/css/acoordeon.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!--<link href="/assets/css/css_alt.css" rel="stylesheet" type="text/css" />-->
        <link href="/assets/css/style.css" rel="stylesheet" type="text/css" />
        <link href="/assets/css/bootstrap.css" rel="stylesheet" type="text/css" />
        
        <script type="text/javascript" src="/assets/js/jquery.js"></script>
        <script type="text/javascript" src="/assets/js/acoordeon.js"></script>
    </head>
    <body>
        <div id="bg">
            <div id="outer">
                <div id="header">
                    <div id="logo">
                        <h1>
                            <a href="/admin/">
                                <img src="/assets/imagens/simova_logo.png"></img>
                            </a>
                        </h1>
                    </div>
                    <div id="nav">
                        <h1 id="faixa">Painel Admininstrativo</h1>
                        <br class="clear"/>
                    </div>
                </div>
                <div id="main">
                    <div id="sidebar">
                        <h3 id="tam">
                            Menu
                        </h3>
                        <ul id="menuGeral">
                            <li>
                                <a class="itemMenu">Administrador</a>
                                <div class="conteudoMenu">
                                    <a href="paginas/editarPerfil.html" target="principal">Editar Perfil</a>

                                </div>
                            </li>
                            <li>
                                <a class="itemMenu">Funcionários</a>
                                <div class="conteudoMenu">
                                    <a href="paginas/consultarFuncionarios.html" target="principal">Consultar</a>
                                    <a href="/admin/pessoa/cadastro">Cadastrar</a>

                                </div>
                            </li>
                            <li><a class="itemMenu">Pacientes</a>
                                <div class="conteudoMenu">
                                    <a href="paginas/consultarUsuarios.html" target="principal">Consultar</a>
                                    <a href="paginas/cadastrarUsuarios.html" target="principal">Cadastrar</a>

                                </div>
                            </li>
                            <li><a class="itemMenu">Vacinas</a>
                                <div class="conteudoMenu">
                                    <a href="paginas/consultarVacinas.html" target="principal">Consultar</a>
                                    <a href="paginas/cadastrarVacinas.html" target="principal">Cadastrar</a>

                                </div>
                            </li>
                            <li><a class="itemMenu">Calendários de Vacinas</a>
                                <div class="conteudoMenu">
                                    <a href="paginas/consultarVacinas.html" target="principal">Consultar</a>
                                    <a href="paginas/cadastrarVacinas.html" target="principal">Cadastrar</a>

                                </div>
                            </li>
                            <li><a class="itemMenu">Cartão de Vacinas</a>
                                <div class="conteudoMenu">
                                    <a href="paginas/consultarVacinas.html" target="principal">Consultar</a>
                                    <a href="paginas/cadastrarVacinas.html" target="principal">Cadastrar</a>
                                </div>
                            </li>
                        </ul>                   
                    </div>
                    <?php echo $this->layout()->content ?>
<!--                    <iframe src="paginas/principal.html" name="principal">
                        <div id="content">
                            <h1>Seja bem-vindo administrador!<h1>
                                    <br class="clear" />
                                    </div>
                                    </iframe>-->
                </div>
                <div id="copyright">
                    &copy; SIMOVA - Sistema de Monitoramento de Vacinas 
                </div>
            </div>
        </div>
    </body>
</html>
