<script type="text/javascript" src="/admin/js/pessoa.js"></script>
<fieldset>
    <legend>Enviar Mensagens</legend>
    <?php
    if ($this->mensagem):
        ?>
        <div class="alert <?php echo $this->mensagem['type'] ?>"><?php echo $this->mensagem['mensagem'] ?></div>
        <?php
    endif;
    ?>

    <div style="margin-bottom: 18px;" class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab1">Escrever</a></li>
            <li class=""><a data-toggle="tab" href="#tab2">Selecionar Destinatário</a></li>

        </ul>
        <form class="form-horizontal" method="post">
            <div class="tab-content">
                <div id="tab1" class="tab-pane active">

                    <!--INICIO DO PRIMEIRO MENU-->

                    <div class="rows-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label for="inputEmail" class="control-label">Mensagem:</label>
                                <div class="controls">
                                    <textarea rows="3" style="width: 500px;"></textarea>
                                </div>
                            </div>



                        </div>

                    </div>
                    <!--  <div class="rows-fluid">
                          <div class="span12">
                              <div class="form-actions">
                                  <div class="control-group">
                                      <a class="btn btn-primary" href="#tab2" data-toggle="tab">Continuar <i class="icon-forward icon-white"></i></a>
                                  </div>
                              </div>
                          </div>
                      </div>-->

                </div> <!--FIM DO PRIMEIRO MENU-->

                <div id="tab2" class="tab-pane">

                    <!--INICIO DO SEGUNDO MENU-->

                    <div class="rows-fluid ">
                        <div class="span10">
                            <select name="tipoConsulta">
                                <option value="">Selecione a opção</option>
                                <option value="nome">Nome do Paciente</option>
                                <option value="nome">Registro de Nascimento</option>
                                <option value="nome">RG</option>
                                <option value="nome">Data de Nascimento</option>
                                <option value="">Todos</option>
                            </select>
                            <div class="input-append">
                                <input class="input-large" name="search" id="appendedInputButton" type="text">
                                <button type="submit" class="btn btn-info"><i class="icon-search icon-white"></i>&nbsp;Pesquisar</button>
                            </div>
                        </div>

                        <br><br><br><br>

                        <div class="rows-fluid ">
                            <div class="span12">

                                <!--ABAIXO APARECERÁ A LISTA COM OS RESULTADOS DA CONSULTA-->

                                <!--PAGINAÇÃO DAS TABELAS DA PESQUISA-->

                                <table class="table table-bordered table-striped" style="font-size: 13px;">
                                    <thead style="background-color: #08c; color: #FFFFFF">
                                        <tr>
                                            <th rowspan="2">Código do Paciente</th>
                                            <th rowspan="2">Nome do Paciente</th>
                                            <th rowspan="2">Nome da Mãe</th>
                                            <th rowspan="2">RG</th>
                                            <th rowspan="2">Registro de Nascimento</th>
                                            <th rowspan="2">Data de Nascimento</th>
                                            <th>Enviar</th>
                                        </tr>
                                    </thead> 
                                    <tbody>

                                        <tr>
                                            <td colspan="6"></td>
                                            <td><label class="checkbox inline">
                                                    <input type="checkbox" id="inlineCheckbox1" value="option1"> Todos
                                                </label></td>
                                        </tr>
                                        <tr>
                                            <td>18</td>
                                            <td>Joaquim Gomes</td>
                                            <td>Francisca Gomes</td>
                                            <td>5568485</td>
                                            <td>6548785</td>
                                            <td>15/08/1980</td>
                                            <td>
                                                <label class="checkbox inline">
                                                    <input type="checkbox" id="inlineCheckbox1" value="option1"> Sim
                                                </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>16</td>
                                            <td>Mario Brito</td>
                                            <td>Marta Pereira</td>
                                            <td>11111485</td>
                                            <td>2228785</td>
                                            <td>03/05/1980</td>
                                            <td>
                                                <label class="checkbox inline">
                                                    <input type="checkbox" id="inlineCheckbox1" value="option1"> Sim
                                                </label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>02</td>
                                            <td>Maria Sousa</td>
                                            <td>Luzia Sauro</td>
                                            <td>4444485</td>
                                            <td>99999855</td>
                                            <td>01/06/1980</td>
                                            <td>
                                                <label class="checkbox inline">
                                                    <input type="checkbox" id="inlineCheckbox1" value="option1"> Sim
                                                </label>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                                <div class="pagination pagination-centered">
                                    <ul>
                                        <!--TABELA COM OS DADOS DA PESQUISA-->
                                        <li><a href="#">Anterior</a></li>
                                        <li><a href="#">1</a></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">5</a></li>
                                        <li><a href="#">6</a></li>
                                        <li><a href="#">7</a></li>
                                        <li><a href="#">Proximo</a></li>
                                    </ul>
                                </div>

                            </div> 
                        </div>

                    </div>

                    <div class="rows-fluid">
                        <div class="span12">
                            <div class="form-actions">
                                <div class="control-group">
                                    <button class="btn btn-primary" type="submit">Enviar</button>
                                    <button class="btn btn-primary" type="reset">Limpar</button>
                                </div>
                            </div>
                        </div>
                    </div> 
                </div> <!--FIM DO SEGUNDO MENU-->
            </div>
        </form>



    </div>
</fieldset>

